// Copyright 2016, 2015, 2014 Matthias Koch
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System;
using System.Collections.Generic;
using System.Linq;

namespace Coconut.VsSettingsSwitch
{
  public static class KeyboardSchemes
  {
    public static ILookup<string, string[]> ReSharper =
        new Dictionary<string, string[]>
        {
          { "ReSharper.ReSharper_ShowFindResults", new[] { "Text Editor::Ctrl+Alt+F12", "XAML UI Designer::Ctrl+Alt+F12", "Global::Ctrl+Alt+F12" } },
          { "ReSharper.ReSharper_ShowCodeStructure", new[] { "XAML UI Designer::Ctrl+Alt+F", "Global::Ctrl+Alt+F", "Text Editor::Ctrl+Alt+F" } },
          { "ReSharper.ReSharper_ShowTodoExplorer", new[] { "Global::Ctrl+Alt+D", "Text Editor::Ctrl+Alt+D", "XAML UI Designer::Ctrl+Alt+D" } },
          { "ReSharper.ReSharper_ShowUnitTestExplorer", new[] { "Text Editor::Ctrl+Alt+U", "Global::Ctrl+Alt+U", "XAML UI Designer::Ctrl+Alt+U" } },
          { "ReSharper.ReSharper_ShowUnitTestSessions", new[] { "Text Editor::Ctrl+Alt+T", "XAML UI Designer::Ctrl+Alt+T", "Global::Ctrl+Alt+T" } },
          { "ReSharper.ReSharper_FindUsages", new[] { "Global::Shift+F12", "Text Editor::Shift+F12", "XAML UI Designer::Shift+F12" } },
          { "ReSharper.ReSharper_FindUsagesAdvanced", new[] { "Global::Ctrl+Shift+Alt+F12", "Text Editor::Ctrl+Shift+Alt+F12", "XAML UI Designer::Ctrl+Shift+Alt+F12" } },
          { "ReSharper.ReSharper_HighlightUsages", new[] { "Text Editor::Shift+Alt+F11", "XAML UI Designer::Shift+Alt+F11", "Global::Shift+Alt+F11" } },
          { "ReSharper.ReSharper_ResultListGoToPrevLocation", new[] { "Global::Ctrl+Alt+PgUp", "Text Editor::Ctrl+Alt+PgUp", "XAML UI Designer::Ctrl+Alt+PgUp" } },
          { "ReSharper.ReSharper_ResultListGoToNextLocation", new[] { "Text Editor::Ctrl+Alt+PgDn", "XAML UI Designer::Ctrl+Alt+PgDn", "Global::Ctrl+Alt+PgDn" } },
          { "ReSharper.ReSharper_LocateInSolutionOrAssemblyExplorer", new[] { "Global::Shift+Alt+L", "XAML UI Designer::Shift+Alt+L", "Text Editor::Shift+Alt+L" } },
          { "ReSharper.ReSharper_GotoRecentFiles", new[] { "Text Editor::Ctrl+,", "XAML UI Designer::Ctrl+,", "Global::Ctrl+," } },
          { "ReSharper.ReSharper_TypeHierarchyBrowse", new[] { "Text Editor::Ctrl+E, H", "XAML UI Designer::Ctrl+E, Ctrl+H", "Text Editor::Ctrl+E, Ctrl+H", "Global::Ctrl+E, Ctrl+H", "XAML UI Designer::Ctrl+E, H", "Global::Ctrl+E, H" } },
          { "ReSharper.ReSharper_CompleteCodeSmart", new[] { "Text Editor::Ctrl+Alt+Space", "XAML UI Designer::Ctrl+Alt+Space" } },
          { "ReSharper.ReSharper_CompleteCodeTypeName", new[] { "Text Editor::Shift+Alt+Space", "XAML UI Designer::Shift+Alt+Space" } },
          { "ReSharper.ReSharper_LiveTemplatesInsert", new[] { "Text Editor::Ctrl+E, Ctrl+L", "XAML UI Designer::Ctrl+E, Ctrl+L", "Text Editor::Ctrl+E, L", "XAML UI Designer::Ctrl+E, L" } },
          { "ReSharper.ReSharper_SurroundWith", new[] { "Text Editor::Ctrl+E, Ctrl+U", "XAML UI Designer::Ctrl+E, Ctrl+U", "Text Editor::Ctrl+E, U", "XAML UI Designer::Ctrl+E, U" } },
          { "ReSharper.ReSharper_Generate", new[] { "XAML UI Designer::Alt+Ins", "Text Editor::Alt+Ins", "Global::Alt+Ins" } },
          { "ReSharper.ReSharper_MoveUp", new[] { "XAML UI Designer::Ctrl+Shift+Alt+Up Arrow", "Text Editor::Ctrl+Shift+Alt+Up Arrow" } },
          { "ReSharper.ReSharper_MoveDown", new[] { "XAML UI Designer::Ctrl+Shift+Alt+Down Arrow", "Text Editor::Ctrl+Shift+Alt+Down Arrow" } },
          { "ReSharper.ReSharper_MoveLeft", new[] { "XAML UI Designer::Ctrl+Shift+Alt+Left Arrow", "Text Editor::Ctrl+Shift+Alt+Left Arrow" } },
          { "ReSharper.ReSharper_MoveRight", new[] { "XAML UI Designer::Ctrl+Shift+Alt+Right Arrow", "Text Editor::Ctrl+Shift+Alt+Right Arrow" } },
          { "ReSharper.ReSharper_ExtendSelection", new[] { "XAML UI Designer::Ctrl+Alt+Right Arrow", "Text Editor::Ctrl+Alt+Right Arrow" } },
          { "ReSharper.ReSharper_ShrinkSelection", new[] { "Text Editor::Ctrl+Alt+Left Arrow", "XAML UI Designer::Ctrl+Alt+Left Arrow", "Text Editor::Ctrl+Shift+W", "XAML UI Designer::Ctrl+Shift+W" } },
          { "ReSharper.ReSharper_DuplicateText", new[] { "XAML UI Designer::Ctrl+D", "Text Editor::Ctrl+D" } },
          { "ReSharper.ReSharper_LineComment", new[] { "XAML UI Designer::Ctrl+Alt+/", "Text Editor::Ctrl+Alt+/" } },
          { "ReSharper.ReSharper_BlockComment", new[] { "XAML UI Designer::Ctrl+Shift+/", "Text Editor::Ctrl+Shift+/" } },
          { "ReSharper.ReSharper_CleanupCode", new[] { "XAML UI Designer::Ctrl+E, Ctrl+C", "Text Editor::Ctrl+E, Ctrl+C", "Text Editor::Ctrl+E, C", "XAML UI Designer::Ctrl+E, C", "Global::Ctrl+E, Ctrl+C", "Global::Ctrl+E, C" } },
          { "ReSharper.ReSharper_QuickDoc", new[] { "Text Editor::Ctrl+Shift+F1", "Global::Ctrl+Shift+F1", "XAML UI Designer::Ctrl+Shift+F1" } },
          { "ReSharper.ReSharper_PasteMultiple", new[] { "Text Editor::Ctrl+Shift+V", "XAML UI Designer::Ctrl+Shift+V" } },
          { "ReSharper.ReSharper_GotoType", new[] { "Text Editor::Ctrl+T", "XAML UI Designer::Ctrl+T", "Global::Ctrl+T" } },
          { "ReSharper.ReSharper_GotoFile", new[] { "XAML UI Designer::Ctrl+Shift+T", "Text Editor::Ctrl+Shift+T", "Global::Ctrl+Shift+T" } },
          { "ReSharper.ReSharper_GotoFileMember", new[] { "XAML UI Designer::Alt+\\", "Text Editor::Alt+\\", "Global::Alt+\\" } },
          { "ReSharper.ReSharper_GotoSymbol", new[] { "Global::Shift+Alt+T", "Text Editor::Shift+Alt+T", "XAML UI Designer::Shift+Alt+T" } },
          { "ReSharper.ReSharper_NavigateTo", new[] { "Text Editor::Alt+`", "Global::Alt+`", "XAML UI Designer::Alt+`" } },
          { "ReSharper.ReSharper_GotoTypeDeclaration", new[] { "Global::Ctrl+Shift+F11", "Text Editor::Ctrl+Shift+F11", "XAML UI Designer::Ctrl+Shift+F11" } },
          { "ReSharper.ReSharper_GotoBase", new[] { "Global::Alt+Home", "Text Editor::Alt+Home", "XAML UI Designer::Alt+Home" } },
          { "ReSharper.ReSharper_GotoInheritors", new[] { "XAML UI Designer::Alt+End", "Text Editor::Alt+End", "Global::Alt+End" } },
          { "ReSharper.ReSharper_GotoUsage", new[] { "Global::Shift+Alt+F12", "XAML UI Designer::Shift+Alt+F12", "Text Editor::Shift+Alt+F12" } },
          { "ReSharper.ReSharper_GotoNextMethod", new[] { "Text Editor::Alt+Down Arrow", "XAML UI Designer::Alt+Down Arrow" } },
          { "ReSharper.ReSharper_GotoPrevMethod", new[] { "Text Editor::Alt+Up Arrow", "XAML UI Designer::Alt+Up Arrow" } },
          { "ReSharper.ReSharper_GotoContainingDeclaration", new[] { "XAML UI Designer::Ctrl+[", "Text Editor::Ctrl+[" } },
          { "ReSharper.ReSharper_GotoNextHighlight", new[] { "XAML UI Designer::Alt+PgDn", "Text Editor::Alt+PgDn", "Global::Alt+PgDn" } },
          { "ReSharper.ReSharper_GotoPrevHighlight", new[] { "Global::Alt+PgUp", "Text Editor::Alt+PgUp", "XAML UI Designer::Alt+PgUp" } },
          { "ReSharper.ReSharper_GotoNextErrorInSolution", new[] { "Global::Shift+Alt+PgDn", "Text Editor::Shift+Alt+PgDn", "XAML UI Designer::Shift+Alt+PgDn" } },
          { "ReSharper.ReSharper_GotoPrevErrorInSolution", new[] { "Global::Shift+Alt+PgUp", "Text Editor::Shift+Alt+PgUp", "XAML UI Designer::Shift+Alt+PgUp" } },
          { "ReSharper.ReSharper_GotoLastEditLocation", new[] { "Text Editor::Ctrl+Shift+Bkspce", "Global::Ctrl+Shift+Bkspce", "XAML UI Designer::Ctrl+Shift+Bkspce" } },
          { "ReSharper.ReSharper_ExploreStackTrace", new[] { "Global::Ctrl+E, T", "Text Editor::Ctrl+E, T", "XAML UI Designer::Ctrl+E, Ctrl+T", "Text Editor::Ctrl+E, Ctrl+T", "Global::Ctrl+E, Ctrl+T", "XAML UI Designer::Ctrl+E, T" } },
          { "ReSharper.ReSharper_UnitTestRunSolution", new[] { "Text Editor::Ctrl+U, L", "Global::Ctrl+U, L", "Text Editor::Ctrl+U, Ctrl+L", "Global::Ctrl+U, Ctrl+L", "XAML UI Designer::Ctrl+U, L", "XAML UI Designer::Ctrl+U, Ctrl+L" } },
          { "ReSharper.ReSharper_SilentCleanupCode", new[] { "Global::Ctrl+E, F", "Text Editor::Ctrl+E, F", "Global::Ctrl+E, Ctrl+F", "Text Editor::Ctrl+E, Ctrl+F", "XAML UI Designer::Ctrl+E, Ctrl+F", "XAML UI Designer::Ctrl+E, F" } },
          { "ReSharper_ParameterInfoGoToPreviousSignature", new[] { "Global::Ctrl+Shift+Alt+Space", "Text Editor::Ctrl+Shift+Alt+Space", "XAML UI Designer::Ctrl+Shift+Alt+Space" } },
          { "ReSharper_AltEnter", new[] { "Text Editor::Alt+Enter", "XAML UI Designer::Alt+Enter" } },
          { "ReSharper_WindowManagerCloseRecentTool", new[] { "Global::Ctrl+Shift+F4", "Text Editor::Ctrl+Shift+F4", "XAML UI Designer::Ctrl+Shift+F4" } },
          { "ReSharper_WindowManagerActivateRecentTool", new[] { "XAML UI Designer::Ctrl+Alt+Bkspce", "Text Editor::Ctrl+Alt+Bkspce", "Global::Ctrl+Alt+Bkspce" } },
          { "ReSharper_EnableDaemon", new[] { "Global::Ctrl+Shift+Alt+8", "Text Editor::Ctrl+Shift+Alt+8", "XAML UI Designer::Ctrl+Shift+Alt+8" } },
          { "ReSharper.ReSharper_RefactorThis", new[] { "Text Editor::Ctrl+Shift+R", "Global::Ctrl+Shift+R", "XAML UI Designer::Ctrl+Shift+R" } },
          { "ReSharper.ReSharper_Rename", new[] { "XAML UI Designer::Ctrl+R, R", "Text Editor::Ctrl+R, R", "XAML UI Designer::Ctrl+R, Ctrl+R", "Text Editor::Ctrl+R, Ctrl+R" } },
          { "ReSharper.ReSharper_Move", new[] { "Global::Ctrl+R, O", "Text Editor::Ctrl+R, Ctrl+O", "Global::Ctrl+R, Ctrl+O", "XAML UI Designer::Ctrl+R, O", "Text Editor::Ctrl+R, O", "XAML UI Designer::Ctrl+R, Ctrl+O" } },
          { "ReSharper.ReSharper_SafeDelete", new[] { "Text Editor::Alt+Del", "Global::Alt+Del", "XAML UI Designer::Ctrl+R, Ctrl+D", "Text Editor::Ctrl+R, Ctrl+D", "Global::Ctrl+R, D", "XAML UI Designer::Ctrl+R, D", "Text Editor::Ctrl+R, D", "Global::Ctrl+R, Ctrl+D", "XAML UI Designer::Alt+Del" } },
          { "ReSharper.ReSharper_ExtractMethod", new[] { "Text Editor::Ctrl+R, M", "Global::Ctrl+R, M", "Global::Ctrl+R, Ctrl+M", "XAML UI Designer::Ctrl+R, M", "XAML UI Designer::Ctrl+R, Ctrl+M", "Text Editor::Ctrl+R, Ctrl+M" } },
          { "ReSharper.ReSharper_IntroVariable", new[] { "XAML UI Designer::Ctrl+R, Ctrl+V", "XAML UI Designer::Ctrl+R, V", "Text Editor::Ctrl+R, V", "Text Editor::Ctrl+R, Ctrl+V" } },
          { "ReSharper.ReSharper_IntroduceField", new[] { "XAML UI Designer::Ctrl+R, Ctrl+F", "Text Editor::Ctrl+R, Ctrl+F", "XAML UI Designer::Ctrl+R, F", "Text Editor::Ctrl+R, F" } },
          { "ReSharper.ReSharper_IntroduceParameter", new[] { "XAML UI Designer::Ctrl+R, Ctrl+P", "Text Editor::Ctrl+R, Ctrl+P", "Global::Ctrl+R, Ctrl+P", "XAML UI Designer::Ctrl+R, P", "Text Editor::Ctrl+R, P", "Global::Ctrl+R, P" } },
          { "ReSharper.ReSharper_InlineVariable", new[] { "Text Editor::Ctrl+R, I", "XAML UI Designer::Ctrl+R, I", "Text Editor::Ctrl+R, Ctrl+I", "XAML UI Designer::Ctrl+R, Ctrl+I" } },
          { "ReSharper.ReSharper_EncapsulateField", new[] { "Global::Ctrl+R, E", "Text Editor::Ctrl+R, E", "XAML UI Designer::Ctrl+R, E", "Global::Ctrl+R, Ctrl+E", "Text Editor::Ctrl+R, Ctrl+E", "XAML UI Designer::Ctrl+R, Ctrl+E" } },
          { "ReSharper.ReSharper_ChangeSignature", new[] { "Text Editor::Ctrl+R, Ctrl+S", "Global::Ctrl+R, Ctrl+S", "XAML UI Designer::Ctrl+R, S", "Text Editor::Ctrl+R, S", "Global::Ctrl+R, S", "XAML UI Designer::Ctrl+R, Ctrl+S" } },
          { "ReSharper_ForceCompleteItem", new[] { "XAML UI Designer::Ctrl+Enter", "Text Editor::Ctrl+Enter" } },
          { "ReSharper.ReSharper_UnitTestSessionAppendTests", new[] { "Global::Ctrl+U, A", "Text Editor::Ctrl+U, A", "XAML UI Designer::Ctrl+U, A", "Global::Ctrl+U, Ctrl+A", "Text Editor::Ctrl+U, Ctrl+A", "XAML UI Designer::Ctrl+U, Ctrl+A" } },
          { "ReSharper.ReSharper_UnitTestSessionNewSession", new[] { "XAML UI Designer::Ctrl+U, Ctrl+N", "Global::Ctrl+U, N", "Text Editor::Ctrl+U, N", "XAML UI Designer::Ctrl+U, N", "Global::Ctrl+U, Ctrl+N", "Text Editor::Ctrl+U, Ctrl+N" } },
          { "ReSharper.ReSharper_GotoRecentEdits", new[] { "Global::Ctrl+Shift+,", "Text Editor::Ctrl+Shift+,", "XAML UI Designer::Ctrl+Shift+," } },
          { "ReSharper.ReSharper_UnitTestRunCurrentSession", new[] { "Global::Ctrl+U, Y", "Text Editor::Ctrl+U, Y", "XAML UI Designer::Ctrl+U, Y", "Global::Ctrl+U, Ctrl+Y", "XAML UI Designer::Ctrl+U, Ctrl+Y", "Text Editor::Ctrl+U, Ctrl+Y" } },
          { "ReSharper.ReSharper_ShowInspectionWindow", new[] { "Global::Ctrl+Alt+V", "Text Editor::Ctrl+Alt+V", "XAML UI Designer::Ctrl+Alt+V" } },
          { "ReSharper.ReSharper_InspectThis", new[] { "XAML UI Designer::Ctrl+Shift+Alt+A", "Global::Ctrl+Shift+Alt+A", "Text Editor::Ctrl+Shift+Alt+A" } },
          { "ReSharper_CurrentConfigRunAlt", new[] { "Global::Ctrl+Alt+F5", "Text Editor::Ctrl+Alt+F5", "XAML UI Designer::Ctrl+Alt+F5" } },
          { "ReSharper_CurrentConfigDebugAlt", new[] { "XAML UI Designer::Alt+F5", "Text Editor::Alt+F5", "Global::Alt+F5" } },
          { "ReSharper_BookmarksToggleBookmark0", new[] { "XAML UI Designer::Ctrl+Shift+0", "Text Editor::Ctrl+Shift+0", "Global::Ctrl+Shift+0" } },
          { "ReSharper_BookmarksToggleBookmark1", new[] { "Global::Ctrl+Shift+1", "XAML UI Designer::Ctrl+Shift+1", "Text Editor::Ctrl+Shift+1" } },
          { "ReSharper_BookmarksToggleBookmark2", new[] { "Global::Ctrl+Shift+2", "XAML UI Designer::Ctrl+Shift+2", "Text Editor::Ctrl+Shift+2" } },
          { "ReSharper_BookmarksToggleBookmark3", new[] { "Global::Ctrl+Shift+3", "Text Editor::Ctrl+Shift+3", "XAML UI Designer::Ctrl+Shift+3" } },
          { "ReSharper_BookmarksToggleBookmark4", new[] { "Text Editor::Ctrl+Shift+4", "XAML UI Designer::Ctrl+Shift+4", "Global::Ctrl+Shift+4" } },
          { "ReSharper_BookmarksToggleBookmark5", new[] { "Global::Ctrl+Shift+5", "Text Editor::Ctrl+Shift+5", "XAML UI Designer::Ctrl+Shift+5" } },
          { "ReSharper_BookmarksToggleBookmark6", new[] { "XAML UI Designer::Ctrl+Shift+6", "Text Editor::Ctrl+Shift+6", "Global::Ctrl+Shift+6" } },
          { "ReSharper_BookmarksToggleBookmark7", new[] { "Global::Ctrl+Shift+7", "Text Editor::Ctrl+Shift+7", "XAML UI Designer::Ctrl+Shift+7" } },
          { "ReSharper_BookmarksToggleBookmark8", new[] { "Global::Ctrl+Shift+8", "Text Editor::Ctrl+Shift+8", "XAML UI Designer::Ctrl+Shift+8" } },
          { "ReSharper_BookmarksToggleBookmark9", new[] { "Global::Ctrl+Shift+9", "Text Editor::Ctrl+Shift+9", "XAML UI Designer::Ctrl+Shift+9" } },
          { "ReSharper_BookmarksGoToBookmark0", new[] { "Text Editor::Ctrl+0", "XAML UI Designer::Ctrl+0", "Global::Ctrl+0" } },
          { "ReSharper_BookmarksGoToBookmark1", new[] { "XAML UI Designer::Ctrl+1", "Text Editor::Ctrl+1", "Global::Ctrl+1" } },
          { "ReSharper_BookmarksGoToBookmark2", new[] { "XAML UI Designer::Ctrl+2", "Text Editor::Ctrl+2", "Global::Ctrl+2" } },
          { "ReSharper_BookmarksGoToBookmark3", new[] { "Text Editor::Ctrl+3", "Global::Ctrl+3", "XAML UI Designer::Ctrl+3" } },
          { "ReSharper_BookmarksGoToBookmark4", new[] { "Global::Ctrl+4", "Text Editor::Ctrl+4", "XAML UI Designer::Ctrl+4" } },
          { "ReSharper_BookmarksGoToBookmark5", new[] { "Global::Ctrl+5", "Text Editor::Ctrl+5", "XAML UI Designer::Ctrl+5" } },
          { "ReSharper_BookmarksGoToBookmark6", new[] { "XAML UI Designer::Ctrl+6", "Text Editor::Ctrl+6", "Global::Ctrl+6" } },
          { "ReSharper_BookmarksGoToBookmark7", new[] { "Global::Ctrl+7", "Text Editor::Ctrl+7", "XAML UI Designer::Ctrl+7" } },
          { "ReSharper_BookmarksGoToBookmark8", new[] { "XAML UI Designer::Ctrl+8", "Text Editor::Ctrl+8", "Global::Ctrl+8" } },
          { "ReSharper_BookmarksGoToBookmark9", new[] { "XAML UI Designer::Ctrl+9", "Text Editor::Ctrl+9", "Global::Ctrl+9" } },
          { "ReSharper.ReSharper_BookmarksBookmarksMenu", new[] { "XAML UI Designer::Ctrl+`", "Text Editor::Ctrl+`", "Global::Ctrl+`" } },
          { "ReSharper.ReSharper_GotoRelatedFiles", new[] { "Text Editor::Ctrl+Alt+F7", "Global::Ctrl+Alt+F7", "XAML UI Designer::Ctrl+Alt+F7" } },
          { "ReSharper_SelectContainingDeclaration", new[] { "XAML UI Designer::Ctrl+Shift+[", "Text Editor::Ctrl+Shift+[", "Global::Ctrl+Shift+[" } },
          { "ReSharper.ReSharper_GenerateFileBesides", new[] { "Text Editor::Ctrl+Alt+Ins", "XAML UI Designer::Ctrl+Alt+Ins", "Global::Ctrl+Alt+Ins" } },
          { "ReSharper.ReSharper_UnitTestSessionRepeatPreviousRun", new[] { "Text Editor::Ctrl+U, Ctrl+U", "Global::Ctrl+U, U", "Text Editor::Ctrl+U, U", "XAML UI Designer::Ctrl+U, U", "Global::Ctrl+U, Ctrl+U", "XAML UI Designer::Ctrl+U, Ctrl+U" } },
          { "ReSharper_TemplateCompleteItem", new[] { "XAML UI Designer::Shift+Enter", "Text Editor::Shift+Enter" } },
          { "ReSharper.ReSharper_UnitTestRunFromContext", new[] { "Text Editor::Ctrl+U, Ctrl+R", "Global::Ctrl+U, Ctrl+R", "XAML UI Designer::Ctrl+U, R", "Text Editor::Ctrl+U, R", "Global::Ctrl+U, R", "XAML UI Designer::Ctrl+U, Ctrl+R" } },
          { "ReSharper.ReSharper_UnitTestDebugContext", new[] { "Global::Ctrl+U, D", "XAML UI Designer::Ctrl+U, D", "Global::Ctrl+U, Ctrl+D", "Text Editor::Ctrl+U, Ctrl+D", "XAML UI Designer::Ctrl+U, Ctrl+D", "Text Editor::Ctrl+U, D" } },
          { "ReSharper.ReSharper_OptimizeReferences", new[] { "Global::Ctrl+Alt+Y", "XAML UI Designer::Ctrl+Alt+Y", "Text Editor::Ctrl+Alt+Y" } },
          { "ReSharper_PeekDefinition", new[] { "Text Editor::Ctrl+Shift+Q", "XAML UI Designer::Ctrl+Shift+Q" } },
          { "ReSharper.ReSharper_GotoAction", new[] { "Global::Ctrl+Shift+A", "Text Editor::Ctrl+Shift+A", "XAML UI Designer::Ctrl+Shift+A" } },
          { "ReSharper.ReSharper_RunConfigSettings", new[] { "Global::Ctrl+Shift+Alt+R", "Text Editor::Ctrl+Shift+Alt+R", "XAML UI Designer::Ctrl+Shift+Alt+R" } },
          { "ReSharper.ReSharper_GotoNextBlock", new[] { "XAML UI Designer::Ctrl+Alt+]", "Text Editor::Ctrl+Alt+]" } },
          { "ReSharper_ExecuteDeferredRename", new[] { "XAML UI Designer::Ctrl+Shift+Alt+Enter", "Text Editor::Ctrl+Shift+Alt+Enter" } },
          { "ReSharper.ReSharper_ApplyCodeStyle", new[] { "Global::Ctrl+Alt+S", "Text Editor::Ctrl+Alt+S", "XAML UI Designer::Ctrl+Alt+S" } },
          { "ReSharper_ToggleInternal", new[] { "Text Editor::Ctrl+Shift+Alt+0", "Global::Ctrl+Shift+Alt+0", "XAML UI Designer::Ctrl+Shift+Alt+0" } },
          { "ReSharper.ReSharper_GotoPrevBlock", new[] { "Text Editor::Ctrl+Alt+[", "XAML UI Designer::Ctrl+Alt+[" } },
          { "ReSharper.ReSharper_ReformatCode", new[] { "XAML UI Designer::Ctrl+Alt+Enter", "Text Editor::Ctrl+Alt+Enter", "Global::Ctrl+Alt+Enter" } },
          { "ReSharper_GlobalThrowException", new[] { "Global::Ctrl+Shift+Alt+F9", "Text Editor::Ctrl+Shift+Alt+F9", "XAML UI Designer::Ctrl+Shift+Alt+F9" } },
          { "ReSharper.ReSharper_ProfileAllTestsFromSolutionWithMemoryUnit", new[] { "Text Editor::Ctrl+U, Ctrl+E", "XAML UI Designer::Ctrl+U, Ctrl+E", "Global::Ctrl+U, E", "Text Editor::Ctrl+U, E", "XAML UI Designer::Ctrl+U, E", "Global::Ctrl+U, Ctrl+E" } },
          { "ReSharper.ReSharper_ProfileAllTestsInCurrentContextWithMemoryUnit", new[] { "Text Editor::Ctrl+U, Ctrl+M", "XAML UI Designer::Ctrl+U, Ctrl+M", "Global::Ctrl+U, Ctrl+M", "XAML UI Designer::Ctrl+U, M", "Text Editor::Ctrl+U, M", "Global::Ctrl+U, M" } }
        }.ToLookup(x => x.Key, x => x.Value);

    public static Dictionary<string, object[]> VisualCSharp =
        new Dictionary<string, object[]>
        {
          { "View.NextError", new object[] { "Global::Ctrl+Shift+F12" } },
          { "Format.AlignBottoms", new object[] { "VC Dialog Editor::Ctrl+Shift+Down Arrow" } },
          { "Format.AlignMiddles", new object[] { "VC Dialog Editor::F9" } },
          { "Format.AlignLefts", new object[] { "VC Dialog Editor::Ctrl+Shift+Left Arrow" } },
          { "Format.AlignRights", new object[] { "VC Dialog Editor::Ctrl+Shift+Right Arrow" } },
          { "Format.AlignTops", new object[] { "VC Dialog Editor::Ctrl+Shift+Up Arrow" } },
          { "Format.AlignCenters", new object[] { "VC Dialog Editor::Shift+F9" } },
          { "Edit.Copy", new object[] { "Global::Ctrl+C", "Global::Ctrl+Ins" } },
          { "Edit.Cut", new object[] { "Global::Ctrl+X", "Global::Shift+Del" } },
          { "Edit.Delete", new object[] { "Global::Del", "Class Diagram::Ctrl+Del", "Team Explorer::Del" } },
          { "Edit.Paste", new object[] { "Global::Ctrl+V", "Global::Shift+Ins" } },
          { "File.Print", new object[] { "Global::Ctrl+P" } },
          { "Edit.Redo", new object[] { "Global::Ctrl+Y", "Global::Ctrl+Shift+Z", "Global::Shift+Alt+Bkspce" } },
          { "Edit.SelectAll", new object[] { "Global::Ctrl+A" } },
          { "View.Toolbox", new object[] { "Global::Ctrl+Alt+X", "Global::Ctrl+W, X", "Global::Ctrl+W, Ctrl+X" } },
          { "Edit.Undo", new object[] { "Global::Ctrl+Z", "Global::Alt+Bkspce" } },
          { "Format.Bold", new object[] { "HTML Editor Design View::Ctrl+B" } },
          { "Format.Italic", new object[] { "HTML Editor Design View::Ctrl+I" } },
          { "Format.Underline", new object[] { "HTML Editor Design View::Ctrl+U" } },
          { "Edit.Find", new object[] { "Global::Ctrl+F" } },
          { "QueryDesigner.SQL", new object[] { "Query Designer::Ctrl+3", "View Designer::Ctrl+3" } },
          { "QueryDesigner.Diagram", new object[] { "Query Designer::Ctrl+1", "View Designer::Ctrl+1" } },
          { "QueryDesigner.Results", new object[] { "Query Designer::Ctrl+4", "View Designer::Ctrl+4" } },
          { "QueryDesigner.Criteria", new object[] { "Query Designer::Ctrl+2", "View Designer::Ctrl+2" } },
          { "File.Rename", new object[] { "Team Explorer::F2" } },
          { "Edit.Remove", new object[] { "Managed Resources Editor::Del" } },
          { "Debug.StopDebugging", new object[] { "Global::Shift+F5" } },
          { "Debug.BreakAll", new object[] { "Global::Ctrl+Alt+Break" } },
          { "View.Refresh", new object[] { "Team Explorer::F5", "Team Foundation Build Detail Editor::F5" } },
          { "QueryDesigner.ExecuteSQL", new object[] { "Query Designer::Ctrl+R", "View Designer::Ctrl+R" } },
          { "QueryDesigner.GotoRow", new object[] { "Query Designer::Ctrl+G", "View Designer::Ctrl+G" } },
          { "Debug.Threads", new object[] { "Global::Ctrl+Alt+H", "Global::Ctrl+D, T", "Global::Ctrl+D, Ctrl+T" } },
          { "File.NewProject", new object[] { "Global::Ctrl+Shift+N" } },
          { "File.OpenProject", new object[] { "Global::Ctrl+Shift+O" } },
          { "Project.AddNewItem", new object[] { "Global::Ctrl+Shift+A" } },
          { "File.NewFile", new object[] { "Global::Ctrl+N" } },
          { "File.OpenFile", new object[] { "Global::Ctrl+O" } },
          { "File.SaveAll", new object[] { "Global::Ctrl+Shift+S" } },
          { "File.Exit", new object[] { "Global::Alt+F4" } },
          { "Edit.Replace", new object[] { "Global::Ctrl+H" } },
          { "Edit.GoTo", new object[] { "Global::Ctrl+G" } },
          { "View.PropertyPages", new object[] { "Global::Shift+F4" } },
          { "View.FullScreen", new object[] { "Global::Shift+Alt+Enter" } },
          { "View.SolutionExplorer", new object[] { "Global::Ctrl+Alt+L", "Global::Ctrl+W, S", "Global::Ctrl+W, Ctrl+S" } },
          { "View.PropertiesWindow", new object[] { "Global::F4", "Global::Ctrl+W, P", "Global::Ctrl+W, Ctrl+P" } },
          { "View.TaskList", new object[] { "Global::Ctrl+^, T", "Global::Ctrl+^, Ctrl+T", "Global::Ctrl+W, T", "Global::Ctrl+W, Ctrl+T" } },
          { "View.Output", new object[] { "Global::Ctrl+Alt+O", "Global::Ctrl+W, O", "Global::Ctrl+W, Ctrl+O" } },
          { "View.ObjectBrowser", new object[] { "Global::Ctrl+Alt+J", "Global::Ctrl+W, J", "Global::Ctrl+W, Ctrl+J" } },
          { "View.DocumentOutline", new object[] { "Global::Ctrl+Alt+T", "Global::Ctrl+W, U", "Global::Ctrl+W, Ctrl+U" } },
          { "Debug.Immediate", new object[] { "Global::Ctrl+Alt+I", "Global::Ctrl+D, I", "Global::Ctrl+D, Ctrl+I" } },
          { "Debug.Locals", new object[] { "Global::Ctrl+Alt+V, L", "Global::Ctrl+D, L", "Global::Ctrl+D, Ctrl+L" } },
          { "Debug.CallStack", new object[] { "Global::Ctrl+Alt+C", "Global::Ctrl+D, C", "Global::Ctrl+D, Ctrl+C" } },
          { "Project.AddExistingItem", new object[] { "Global::Shift+Alt+A" } },
          { "Debug.StepInto", new object[] { "Global::F11" } },
          { "Debug.StepOver", new object[] { "Global::F10" } },
          { "Debug.StepOut", new object[] { "Global::Shift+F11" } },
          { "Debug.RunToCursor", new object[] { "Global::Ctrl+F10" } },
          { "Debug.QuickWatch", new object[] { "Global::Shift+F9", "Global::Ctrl+Alt+Q", "Global::Ctrl+D, Q", "Global::Ctrl+D, Ctrl+Q" } },
          { "Debug.ToggleBreakpoint", new object[] { "Global::F9" } },
          { "Debug.DeleteAllBreakpoints", new object[] { "Global::Ctrl+Shift+F9" } },
          { "Debug.SetNextStatement", new object[] { "Global::Ctrl+Shift+F10" } },
          { "Debug.ShowNextStatement", new object[] { "Global::Alt+Num *" } },
          { "Edit.FindinFiles", new object[] { "Global::Ctrl+Shift+F" } },
          { "Edit.ReplaceinFiles", new object[] { "Global::Ctrl+Shift+H" } },
          { "Edit.GoToNextLocation", new object[] { "Global::F8" } },
          { "Edit.GoToPrevLocation", new object[] { "Global::Shift+F8" } },
          { "Window.NextTab", new object[] { "Global::Ctrl+Alt+PgDn", "Global::Ctrl+PgDn" } },
          { "Window.PreviousTab", new object[] { "Global::Ctrl+Alt+PgUp", "Global::Ctrl+PgUp", "HTML Editor Source View::Ctrl+PgUp", "HTML Editor Design View::Ctrl+PgUp" } },
          { "Window.CloseToolWindow", new object[] { "Global::Shift+Esc" } },
          { "Window.ActivateDocumentWindow", new object[] { "Global::Esc" } },
          { "Window.MovetoNavigationBar", new object[] { "Global::Ctrl+F2" } },
          { "Debug.Start", new object[] { "Global::F5" } },
          { "Debug.Restart", new object[] { "Global::Ctrl+Shift+F5" } },
          { "Window.NextPane", new object[] { "Global::Alt+F6" } },
          { "Window.PreviousPane", new object[] { "Global::Shift+Alt+F6" } },
          { "View.ErrorList", new object[] { "Global::Ctrl+^, E", "Global::Ctrl+^, Ctrl+E", "Global::Ctrl+W, E", "Global::Ctrl+W, Ctrl+E" } },
          { "File.SaveSelectedItems", new object[] { "Global::Ctrl+S" } },
          { "View.ViewDesigner", new object[] { "HTML Editor Source View::Shift+F7", "Global::Shift+F7" } },
          { "View.ViewCode", new object[] { "Class Diagram::Enter", "Settings Designer::F7", "Global::F7" } },
          { "View.EditLabel", new object[] { "Global::F2" } },
          { "Debug.Exceptions", new object[] { "Global::Ctrl+Alt+E", "Global::Ctrl+D, E", "Global::Ctrl+D, Ctrl+E" } },
          { "Edit.StopSearch", new object[] { "Global::Alt+F3, S" } },
          { "Debug.StartWithoutDebugging", new object[] { "Global::Ctrl+F5" } },
          { "Edit.FindNext", new object[] { "Global::F3" } },
          { "Edit.FindPrevious", new object[] { "Global::Shift+F3" } },
          { "Edit.FindNextSelected", new object[] { "Global::Ctrl+F3" } },
          { "Edit.FindPreviousSelected", new object[] { "Global::Ctrl+Shift+F3" } },
          { "Debug.EnableBreakpoint", new object[] { "Global::Ctrl+F9" } },
          { "Help.F1Help", new object[] { "Global::F1" } },
          { "ClassViewContextMenus.ClassViewMultiselectProjectreferencesItems.Properties", new object[] { "Global::Alt+Enter" } },
          { "View.ClassView", new object[] { "Global::Ctrl+Shift+C", "Global::Ctrl+W, C", "Global::Ctrl+W, Ctrl+C" } },
          { "Window.NextDocumentWindow", new object[] { "Global::Ctrl+F6" } },
          { "Window.PreviousDocumentWindow", new object[] { "Global::Ctrl+Shift+F6" } },
          { "Edit.CycleClipboardRing", new object[] { "Global::Ctrl+Shift+V", "Global::Ctrl+Shift+Ins" } },
          { "Window.CloseDocumentWindow", new object[] { "Global::Ctrl+F4" } },
          { "View.CommandWindow", new object[] { "Global::Ctrl+Alt+A", "Global::Ctrl+W, A", "Global::Ctrl+W, Ctrl+A" } },
          { "Debug.Autos", new object[] { "Global::Ctrl+Alt+V, A", "Global::Ctrl+D, A", "Global::Ctrl+D, Ctrl+A" } },
          { "View.NavigateBackward", new object[] { "Global::Ctrl+-" } },
          { "View.NavigateForward", new object[] { "Global::Ctrl+Shift+-" } },
          { "Build.BuildSolution", new object[] { "Global::Ctrl+Shift+B", "Global::F6" } },
          { "Build.BuildSelection", new object[] { "Global::Shift+F6" } },
          { "Build.Cancel", new object[] { "Global::Ctrl+Break" } },
          { "Edit.GoToDefinition", new object[] { "Global::F12" } },
          { "Edit.GoToDeclaration", new object[] { "Global::Ctrl+F12" } },
          { "Project.AddClass", new object[] { "Global::Shift+Alt+C" } },
          { "Project.Override", new object[] { "Global::Ctrl+Alt+Ins" } },
          { "View.FindSymbolResults", new object[] { "Global::Ctrl+Alt+F12", "Global::Ctrl+W, Q", "Global::Ctrl+W, Ctrl+Q" } },
          { "View.ResourceView", new object[] { "Global::Ctrl+Shift+E", "Global::Ctrl+W, R", "Global::Ctrl+W, Ctrl+R" } },
          { "Help.WindowHelp", new object[] { "Global::Shift+F1" } },
          { "View.NextView", new object[] { "HTML Editor Source View::Ctrl+PgDn", "HTML Editor Design View::Ctrl+PgDn" } },
          { "Tools.AttachtoProcess", new object[] { "Global::Ctrl+Alt+P" } },
          { "View.PopBrowseContext", new object[] { "Global::Ctrl+Shift+8" } },
          { "View.BrowseNext", new object[] { "Global::Ctrl+Shift+1" } },
          { "View.BrowsePrevious", new object[] { "Global::Ctrl+Shift+2" } },
          { "Edit.QuickFindSymbol", new object[] { "Global::Shift+Alt+F12" } },
          { "View.BookmarkWindow", new object[] { "Global::Ctrl+K, Ctrl+W", "Global::Ctrl+W, B", "Global::Ctrl+W, Ctrl+B" } },
          { "Tools.CodeSnippetsManager", new object[] { "Global::Ctrl+K, Ctrl+B" } },
          { "Window.NextDocumentWindowNav", new object[] { "Global::Ctrl+Tab" } },
          { "Window.PreviousDocumentWindowNav", new object[] { "Global::Ctrl+Shift+Tab" } },
          { "View.ForwardBrowseContext", new object[] { "Global::Ctrl+Shift+7" } },
          { "Edit.FindAllReferences", new object[] { "Global::Ctrl+K, R", "Global::Ctrl+K, Ctrl+R", "Global::Shift+F12" } },
          { "Edit.DeleteBackwards", new object[] { "Text Editor::Bkspce", "Text Editor::Shift+Bkspce" } },
          { "Edit.BreakLine", new object[] { "Text Editor::Enter", "Text Editor::Shift+Enter", "Report Designer::Enter", "Windows Forms Designer::Enter" } },
          { "Edit.InsertTab", new object[] { "Text Editor::Tab", "Report Designer::Tab", "Windows Forms Designer::Tab" } },
          { "Edit.TabLeft", new object[] { "Text Editor::Shift+Tab", "Report Designer::Shift+Tab", "Windows Forms Designer::Shift+Tab" } },
          { "Edit.CharLeft", new object[] { "Text Editor::Left Arrow", "Report Designer::Left Arrow", "Windows Forms Designer::Left Arrow" } },
          { "Edit.CharLeftExtend", new object[] { "Text Editor::Shift+Left Arrow", "Report Designer::Shift+Left Arrow", "Windows Forms Designer::Shift+Left Arrow" } },
          { "Edit.CharRight", new object[] { "Text Editor::Right Arrow", "Report Designer::Right Arrow", "Windows Forms Designer::Right Arrow" } },
          { "Edit.CharRightExtend", new object[] { "Text Editor::Shift+Right Arrow", "Report Designer::Shift+Right Arrow", "Windows Forms Designer::Shift+Right Arrow" } },
          { "Edit.LineUp", new object[] { "Text Editor::Up Arrow", "Report Designer::Up Arrow", "Windows Forms Designer::Up Arrow" } },
          { "Edit.LineUpExtend", new object[] { "Text Editor::Shift+Up Arrow", "Report Designer::Shift+Up Arrow", "Windows Forms Designer::Shift+Down Arrow" } },
          { "Edit.LineDown", new object[] { "Text Editor::Down Arrow", "Report Designer::Down Arrow", "Windows Forms Designer::Down Arrow" } },
          { "Edit.LineDownExtend", new object[] { "Text Editor::Shift+Down Arrow", "Report Designer::Shift+Down Arrow", "Windows Forms Designer::Shift+Up Arrow" } },
          { "Edit.DocumentStart", new object[] { "Text Editor::Ctrl+Home", "Windows Forms Designer::Home" } },
          { "Edit.DocumentStartExtend", new object[] { "Text Editor::Ctrl+Shift+Home", "Windows Forms Designer::Shift+Home" } },
          { "Edit.DocumentEnd", new object[] { "Text Editor::Ctrl+End", "Windows Forms Designer::End" } },
          { "Edit.DocumentEndExtend", new object[] { "Text Editor::Ctrl+Shift+End", "Windows Forms Designer::Shift+End" } },
          { "Edit.LineStart", new object[] { "Text Editor::Home" } },
          { "Edit.LineStartExtend", new object[] { "Text Editor::Shift+Home" } },
          { "Edit.LineEnd", new object[] { "Text Editor::End" } },
          { "Edit.LineEndExtend", new object[] { "Text Editor::Shift+End" } },
          { "Edit.PageUp", new object[] { "Text Editor::PgUp" } },
          { "Edit.PageUpExtend", new object[] { "Text Editor::Shift+PgUp" } },
          { "Edit.PageDown", new object[] { "Text Editor::PgDn" } },
          { "Edit.PageDownExtend", new object[] { "Text Editor::Shift+PgDn" } },
          { "Edit.ViewTop", new object[] { "Text Editor::Ctrl+PgUp" } },
          { "Edit.ViewTopExtend", new object[] { "Text Editor::Ctrl+Shift+PgUp" } },
          { "Edit.ViewBottom", new object[] { "Text Editor::Ctrl+PgDn" } },
          { "Edit.ViewBottomExtend", new object[] { "Text Editor::Ctrl+Shift+PgDn" } },
          { "Edit.ScrollLineUp", new object[] { "Text Editor::Ctrl+Up Arrow", "VC Dialog Editor::Ctrl+Up Arrow" } },
          { "Edit.ScrollLineDown", new object[] { "Text Editor::Ctrl+Down Arrow", "VC Dialog Editor::Ctrl+Down Arrow" } },
          { "Edit.ScrollColumnLeft", new object[] { "VC Dialog Editor::Ctrl+Left Arrow" } },
          { "Edit.ScrollColumnRight", new object[] { "VC Dialog Editor::Ctrl+Right Arrow" } },
          { "Edit.MakeLowercase", new object[] { "Text Editor::Ctrl+U" } },
          { "Edit.MakeUppercase", new object[] { "Text Editor::Ctrl+Shift+U" } },
          { "Edit.SwapAnchor", new object[] { "Text Editor::Ctrl+K, Ctrl+A", "Text Editor::Ctrl+E, A", "Text Editor::Ctrl+E, Ctrl+A" } },
          { "Edit.GotoBrace", new object[] { "Text Editor::Ctrl+´" } },
          { "Edit.GotoBraceExtend", new object[] { "Text Editor::Ctrl+Shift+´" } },
          { "Edit.OvertypeMode", new object[] { "Text Editor::Ins" } },
          { "Edit.LineCut", new object[] { "Text Editor::Ctrl+L" } },
          { "Edit.LineDelete", new object[] { "Text Editor::Ctrl+Shift+L" } },
          { "Edit.DeleteHorizontalWhiteSpace", new object[] { "Text Editor::Ctrl+K, Ctrl+^", "Text Editor::Ctrl+E, ^", "Text Editor::Ctrl+E, Ctrl+^" } },
          { "Edit.LineOpenAbove", new object[] { "Text Editor::Ctrl+Enter" } },
          { "Edit.LineOpenBelow", new object[] { "Text Editor::Ctrl+Shift+Enter" } },
          { "Edit.ClearBookmarks", new object[] { "Text Editor::Ctrl+B, C", "Text Editor::Ctrl+B, Ctrl+C" } },
          { "Edit.ToggleBookmark", new object[] { "Text Editor::Ctrl+K, Ctrl+K", "Text Editor::Ctrl+B, T", "Text Editor::Ctrl+B, Ctrl+T" } },
          { "Edit.NextBookmark", new object[] { "Global::Ctrl+K, Ctrl+N", "Text Editor::Ctrl+B, N", "Text Editor::Ctrl+B, Ctrl+N" } },
          { "Edit.PreviousBookmark", new object[] { "Global::Ctrl+K, Ctrl+P", "Text Editor::Ctrl+B, P", "Text Editor::Ctrl+B, Ctrl+P" } },
          { "Edit.CharTranspose", new object[] { "Text Editor::Ctrl+T" } },
          { "Edit.WordTranspose", new object[] { "Text Editor::Ctrl+Shift+T" } },
          { "Edit.LineTranspose", new object[] { "Text Editor::Shift+Alt+T" } },
          { "Edit.SelectCurrentWord", new object[] { "Global::Ctrl+Shift+W" } },
          { "Edit.WordDeleteToEnd", new object[] { "Text Editor::Ctrl+Del" } },
          { "Edit.WordDeleteToStart", new object[] { "Text Editor::Ctrl+Bkspce" } },
          { "Edit.WordPrevious", new object[] { "Text Editor::Ctrl+Left Arrow" } },
          { "Edit.WordPreviousExtend", new object[] { "Text Editor::Ctrl+Shift+Left Arrow" } },
          { "Edit.WordNext", new object[] { "Text Editor::Ctrl+Right Arrow" } },
          { "Edit.WordNextExtend", new object[] { "Text Editor::Ctrl+Shift+Right Arrow" } },
          { "Edit.SelectionCancel", new object[] { "Text Editor::Esc", "Managed Resources Editor::Esc", "Settings Designer::Esc", "Report Designer::Esc", "Windows Forms Designer::Esc" } },
          { "Edit.ParameterInfo", new object[] { "Text Editor::Ctrl+Shift+Space", "Workflow Designer::Ctrl+K, P", "Workflow Designer::Ctrl+K, Ctrl+P", "Workflow Designer::Ctrl+Shift+Space", "Text Editor::Ctrl+K, P", "Text Editor::Ctrl+K, Ctrl+P" } },
          { "Edit.ViewWhiteSpace", new object[] { "Text Editor::Ctrl+R, Ctrl+W", "Text Editor::Ctrl+E, S", "Text Editor::Ctrl+E, Ctrl+S" } },
          { "Edit.CompleteWord", new object[] { "Text Editor::Ctrl+Space", "Text Editor::Alt+Right Arrow", "Workflow Designer::Ctrl+K, W", "Workflow Designer::Ctrl+K, Ctrl+W", "Workflow Designer::Ctrl+Space", "Workflow Designer::Alt+Right Arrow", "Text Editor::Ctrl+K, W", "Text Editor::Ctrl+K, Ctrl+W" } },
          { "Edit.ListMembers", new object[] { "Text Editor::Ctrl+J", "Workflow Designer::Ctrl+K, L", "Workflow Designer::Ctrl+K, Ctrl+L", "Workflow Designer::Ctrl+J", "Text Editor::Ctrl+K, L", "Text Editor::Ctrl+K, Ctrl+L" } },
          { "Edit.FormatSelection", new object[] { "Text Editor::Ctrl+K, Ctrl+F", "Text Editor::Ctrl+E, F", "Text Editor::Ctrl+E, Ctrl+F" } },
          { "Edit.ToggleTaskListShortcut", new object[] { "Text Editor::Ctrl+K, Ctrl+H", "Text Editor::Ctrl+E, T", "Text Editor::Ctrl+E, Ctrl+T" } },
          { "Edit.QuickInfo", new object[] { "Text Editor::Ctrl+K, Ctrl+I", "Workflow Designer::Ctrl+K, I", "Workflow Designer::Ctrl+K, Ctrl+I", "Text Editor::Ctrl+K, I" } },
          { "Edit.CharLeftExtendColumn", new object[] { "Text Editor::Shift+Alt+Left Arrow" } },
          { "Edit.CharRightExtendColumn", new object[] { "Text Editor::Shift+Alt+Right Arrow" } },
          { "Edit.LineUpExtendColumn", new object[] { "Text Editor::Shift+Alt+Up Arrow" } },
          { "Edit.LineDownExtendColumn", new object[] { "Text Editor::Shift+Alt+Down Arrow" } },
          { "Edit.ToggleWordWrap", new object[] { "Text Editor::Ctrl+E, Ctrl+W", "Text Editor::Ctrl+E, W" } },
          { "Edit.IncrementalSearch", new object[] { "Text Editor::Ctrl+I" } },
          { "Edit.ReverseIncrementalSearch", new object[] { "Text Editor::Ctrl+Shift+I" } },
          { "Edit.LineStartExtendColumn", new object[] { "Text Editor::Shift+Alt+Home" } },
          { "Edit.LineEndExtendColumn", new object[] { "Text Editor::Shift+Alt+End" } },
          { "Edit.WordPreviousExtendColumn", new object[] { "Text Editor::Ctrl+Shift+Alt+Left Arrow" } },
          { "Edit.WordNextExtendColumn", new object[] { "Text Editor::Ctrl+Shift+Alt+Right Arrow" } },
          { "Edit.HideSelection", new object[] { "Text Editor::Ctrl+M, Ctrl+H" } },
          { "Edit.ToggleOutliningExpansion", new object[] { "Text Editor::Ctrl+M, Ctrl+M", "Text Editor::Ctrl+M, M" } },
          { "Edit.ToggleAllOutlining", new object[] { "Text Editor::Ctrl+M, Ctrl+L", "Text Editor::Ctrl+M, L" } },
          { "Edit.StopOutlining", new object[] { "Text Editor::Ctrl+M, Ctrl+P", "Text Editor::Ctrl+M, P" } },
          { "Edit.StopHidingCurrent", new object[] { "Text Editor::Ctrl+M, Ctrl+U" } },
          { "Edit.CollapsetoDefinitions", new object[] { "Text Editor::Ctrl+M, Ctrl+O", "Text Editor::Ctrl+M, O" } },
          { "Edit.CommentSelection", new object[] { "Text Editor::Ctrl+K, Ctrl+C", "Text Editor::Ctrl+E, C", "Text Editor::Ctrl+E, Ctrl+C" } },
          { "Edit.UncommentSelection", new object[] { "Text Editor::Ctrl+K, Ctrl+U", "Text Editor::Ctrl+E, U", "Text Editor::Ctrl+E, Ctrl+U" } },
          { "Edit.OpenFile", new object[] { "Global::Ctrl+Shift+G" } },
          { "Edit.SelectToLastGoBack", new object[] { "Text Editor::Ctrl++" } },
          { "Edit.FormatDocument", new object[] { "Text Editor::Ctrl+K, Ctrl+D", "Text Editor::Ctrl+E, D", "Text Editor::Ctrl+E, Ctrl+D" } },
          { "Edit.IncreaseFilterLevel", new object[] { "Text Editor::Alt+.", "Workflow Designer::Alt+." } },
          { "Edit.DecreaseFilterLevel", new object[] { "Text Editor::Alt+,", "Workflow Designer::Alt+," } },
          { "View.ShowSmartTag", new object[] { "Global::Shift+Alt+F10", "Global::Ctrl+.", "HTML Editor Design View::Shift+Alt+F10" } },
          { "Edit.CopyParameterTip", new object[] { "Text Editor::Ctrl+Shift+Alt+C" } },
          { "Edit.PasteParameterTip", new object[] { "Text Editor::Ctrl+Shift+Alt+P" } },
          { "Format.InsertBookmark", new object[] { "HTML Editor Design View::Ctrl+Shift+L" } },
          { "Format.ConverttoHyperlink", new object[] { "HTML Editor Design View::Ctrl+L" } },
          { "View.EditMaster", new object[] { "HTML Editor Design View::Ctrl+M, Ctrl+M" } },
          { "Edit.InsertSnippet", new object[] { "Global::Ctrl+K, Ctrl+X", "Global::Ctrl+K, X" } },
          { "Edit.CollapseTag", new object[] { "Text Editor::Ctrl+M, Ctrl+T" } },
          { "Build.Compile", new object[] { "Global::Ctrl+F7" } },
          { "Project.AddContentPage", new object[] { "HTML Editor Design View::Ctrl+M, Ctrl+C" } },
          { "View.ViewMarkup", new object[] { "HTML Editor Design View::Shift+F7" } },
          { "Edit.EnableBookmark", new object[] { "Text Editor::Ctrl+B, E", "Text Editor::Ctrl+B, Ctrl+E" } },
          { "Format.TestDialog", new object[] { "VC Dialog Editor::Ctrl+T" } },
          { "Format.SpaceAcross", new object[] { "VC Dialog Editor::Alt+Right Arrow", "VC Dialog Editor::Alt+Left Arrow" } },
          { "Format.SpaceDown", new object[] { "VC Dialog Editor::Alt+Up Arrow", "VC Dialog Editor::Alt+Down Arrow" } },
          { "Format.ToggleGuides", new object[] { "VC Dialog Editor::Ctrl+G" } },
          { "Format.SizetoContent", new object[] { "VC Dialog Editor::Shift+F7" } },
          { "Format.CenterVertical", new object[] { "VC Dialog Editor::Ctrl+F9" } },
          { "Format.CenterHorizontal", new object[] { "VC Dialog Editor::Ctrl+Shift+F9" } },
          { "Format.TabOrder", new object[] { "VC Dialog Editor::Ctrl+D" } },
          { "Format.ButtonRight", new object[] { "VC Dialog Editor::Ctrl+R" } },
          { "Format.ButtonBottom", new object[] { "VC Dialog Editor::Ctrl+B" } },
          { "Edit.MoveControlLeft", new object[] { "Global::Ctrl+Left Arrow", "VC Dialog Editor::Left Arrow", "Report Designer::Ctrl+Left Arrow", "Windows Forms Designer::Ctrl+Left Arrow" } },
          { "Edit.MoveControlDown", new object[] { "Global::Ctrl+Down Arrow", "VC Dialog Editor::Down Arrow", "Report Designer::Ctrl+Down Arrow", "HTML Editor Design View::Ctrl+Down Arrow", "Windows Forms Designer::Ctrl+Down Arrow" } },
          { "Edit.MoveControlRight", new object[] { "Global::Ctrl+Right Arrow", "VC Dialog Editor::Right Arrow", "Report Designer::Ctrl+Right Arrow", "Windows Forms Designer::Ctrl+Right Arrow" } },
          { "Edit.MoveControlUp", new object[] { "Global::Ctrl+Up Arrow", "VC Dialog Editor::Up Arrow", "Report Designer::Ctrl+Up Arrow", "HTML Editor Design View::Ctrl+Up Arrow", "Windows Forms Designer::Ctrl+Up Arrow" } },
          { "Edit.SizeControlDown", new object[] { "Global::Ctrl+Shift+Down Arrow", "VC Dialog Editor::Shift+Down Arrow", "Report Designer::Ctrl+Shift+Down Arrow", "Windows Forms Designer::Ctrl+Shift+Down Arrow" } },
          { "Edit.SizeControlUp", new object[] { "Global::Ctrl+Shift+Up Arrow", "VC Dialog Editor::Shift+Up Arrow", "Report Designer::Ctrl+Shift+Up Arrow", "Windows Forms Designer::Ctrl+Shift+Up Arrow" } },
          { "Edit.SizeControlLeft", new object[] { "Global::Ctrl+Shift+Left Arrow", "VC Dialog Editor::Shift+Left Arrow", "Report Designer::Ctrl+Shift+Left Arrow", "Windows Forms Designer::Ctrl+Shift+Left Arrow" } },
          { "Edit.SizeControlRight", new object[] { "Global::Ctrl+Shift+Right Arrow", "VC Dialog Editor::Shift+Right Arrow", "Report Designer::Ctrl+Shift+Right Arrow", "Windows Forms Designer::Ctrl+Shift+Right Arrow" } },
          { "Edit.NewAccelerator", new object[] { "VC Accelerator Editor::Ins" } },
          { "Edit.NextKeyTyped", new object[] { "VC Accelerator Editor::Ctrl+W" } },
          { "Image.FlipHorizontal", new object[] { "VC Image Editor::Ctrl+H" } },
          { "Image.FlipVertical", new object[] { "VC Image Editor::Shift+Alt+H" } },
          { "Image.Rotate90Degrees", new object[] { "VC Image Editor::Ctrl+Shift+H" } },
          { "Edit.NewString", new object[] { "VC String Editor::Ins" } },
          { "Format.CheckMnemonics", new object[] { "VC Dialog Editor::Ctrl+M" } },
          { "Image.DrawOpaque", new object[] { "VC Image Editor::Ctrl+J" } },
          { "Image.NewImageType", new object[] { "VC Image Editor::Ins" } },
          { "Image.ShowGrid", new object[] { "VC Image Editor::Ctrl+Alt+S" } },
          { "Image.ShowTileGrid", new object[] { "VC Image Editor::Ctrl+Shift+Alt+S" } },
          { "Image.Magnify", new object[] { "VC Image Editor::Ctrl+Shift+M" } },
          { "Image.RectangleSelectionTool", new object[] { "VC Image Editor::Shift+Alt+S" } },
          { "Image.EraseTool", new object[] { "VC Image Editor::Ctrl+Shift+I" } },
          { "Image.FillTool", new object[] { "VC Image Editor::Ctrl+F" } },
          { "Image.PencilTool", new object[] { "VC Image Editor::Ctrl+I" } },
          { "Image.BrushTool", new object[] { "VC Image Editor::Ctrl+B" } },
          { "Image.AirbrushTool", new object[] { "VC Image Editor::Ctrl+A" } },
          { "Image.LineTool", new object[] { "VC Image Editor::Ctrl+L" } },
          { "Image.TextTool", new object[] { "VC Image Editor::Ctrl+T" } },
          { "Image.RectangleTool", new object[] { "VC Image Editor::Alt+R" } },
          { "Image.OutlinedRectangleTool", new object[] { "VC Image Editor::Shift+Alt+R" } },
          { "Image.FilledRectangleTool", new object[] { "VC Image Editor::Ctrl+Shift+Alt+R" } },
          { "Image.RoundedRectangleTool", new object[] { "VC Image Editor::Alt+W" } },
          { "Image.OutlinedRoundedRectangleTool", new object[] { "VC Image Editor::Shift+Alt+W" } },
          { "Image.FilledRoundedRectangleTool", new object[] { "VC Image Editor::Ctrl+Shift+Alt+W" } },
          { "Image.EllipseTool", new object[] { "VC Image Editor::Alt+P" } },
          { "Image.OutlinedEllipseTool", new object[] { "VC Image Editor::Shift+Alt+P" } },
          { "Image.FilledEllipseTool", new object[] { "VC Image Editor::Ctrl+Shift+Alt+P" } },
          { "Image.MagnificationTool", new object[] { "VC Image Editor::Ctrl+M" } },
          { "Image.LargerBrush", new object[] { "VC Image Editor::Ctrl++" } },
          { "Image.SmallBrush", new object[] { "VC Image Editor::Ctrl+." } },
          { "Image.SmallerBrush", new object[] { "VC Image Editor::Ctrl+-" } },
          { "Image.ZoomIn", new object[] { "VC Image Editor::Ctrl+Shift+.", "VC Image Editor::Ctrl+Up Arrow" } },
          { "Image.ZoomOut", new object[] { "VC Image Editor::Ctrl+Shift+,", "VC Image Editor::Ctrl+Down Arrow" } },
          { "Image.PreviousColor", new object[] { "VC Image Editor::Ctrl+ß", "VC Image Editor::Ctrl+Left Arrow" } },
          { "Image.PreviousRightColor", new object[] { "VC Image Editor::Ctrl+Shift+ß", "VC Image Editor::Ctrl+Shift+Left Arrow" } },
          { "Image.NextColor", new object[] { "VC Image Editor::Ctrl+´", "VC Image Editor::Ctrl+Right Arrow" } },
          { "Image.NextRightColor", new object[] { "VC Image Editor::Ctrl+Shift+´", "VC Image Editor::Ctrl+Shift+Right Arrow" } },
          { "Edit.ShowTileGrid", new object[] { "Global::Enter" } },
          { "Edit.MoveControlUpGrid", new object[] { "Global::Up Arrow" } },
          { "Edit.MoveControlDownGrid", new object[] { "Global::Down Arrow" } },
          { "Edit.MoveControlLeftGrid", new object[] { "Global::Left Arrow" } },
          { "Edit.MoveControlRightGrid", new object[] { "Global::Right Arrow" } },
          { "Edit.SizeControlRightGrid", new object[] { "Global::Shift+Right Arrow" } },
          { "Edit.SizeControlUpGrid", new object[] { "Global::Shift+Up Arrow" } },
          { "Edit.SizeControlLeftGrid", new object[] { "Global::Shift+Left Arrow" } },
          { "Edit.SizeControlDownGrid", new object[] { "Global::Shift+Down Arrow" } },
          { "Edit.SelectNextControl", new object[] { "Global::Tab" } },
          { "Edit.SelectPreviousControl", new object[] { "Global::Shift+Tab" } },
          { "Refactor.Rename", new object[] { "Global::Ctrl+R, Ctrl+R", "Global::Ctrl+R, R", "Text Editor::F2" } },
          { "Refactor.ExtractMethod", new object[] { "Global::Ctrl+R, Ctrl+M", "Global::Ctrl+R, M" } },
          { "Refactor.EncapsulateField", new object[] { "Global::Ctrl+R, Ctrl+E", "Global::Ctrl+R, E" } },
          { "Refactor.ExtractInterface", new object[] { "Global::Ctrl+R, Ctrl+I", "Global::Ctrl+R, I" } },
          { "Refactor.RemoveParameters", new object[] { "Global::Ctrl+R, Ctrl+V", "Global::Ctrl+R, V" } },
          { "Refactor.ReorderParameters", new object[] { "Global::Ctrl+R, Ctrl+O", "Global::Ctrl+R, O" } },
          { "Edit.GenerateMethod", new object[] { "Global::Ctrl+K, M", "Global::Ctrl+K, Ctrl+M" } },
          { "Edit.SurroundWith", new object[] { "Global::Ctrl+K, Ctrl+S", "Global::Ctrl+K, S" } },
          { "Window.ShowEzMDIFileList", new object[] { "Global::Ctrl+Alt+Down Arrow" } },
          { "Window.NextToolWindowNav", new object[] { "Global::Alt+F7" } },
          { "Window.PreviousToolWindowNav", new object[] { "Global::Shift+Alt+F7" } },
          { "View.ClassViewGoToSearchCombo", new object[] { "Global::Ctrl+K, Ctrl+V" } },
          { "View.Backward", new object[] { "Global::Alt+Left Arrow" } },
          { "View.Forward", new object[] { "Global::Alt+Right Arrow" } },
          { "View.CodeDefinitionWindow", new object[] { "Global::Ctrl+^, D", "Global::Ctrl+^, Ctrl+D", "Global::Ctrl+W, D", "Global::Ctrl+W, Ctrl+D" } },
          { "View.ServerExplorer", new object[] { "Global::Ctrl+Alt+S", "Global::Ctrl+W, L", "Global::Ctrl+W, Ctrl+L" } },
          { "EditorContextMenus.CodeWindow.ViewCallHierarchy", new object[] { "Global::Ctrl+K, Ctrl+T", "Global::Ctrl+K, T" } },
          { "Edit.ToggleCompletionMode", new object[] { "Text Editor::Ctrl+Alt+Space" } },
          { "Edit.NextHighlightedReference", new object[] { "Text Editor::Ctrl+Shift+Down Arrow" } },
          { "Edit.PreviousHighlightedReference", new object[] { "Text Editor::Ctrl+Shift+Up Arrow" } },
          { "Window.AddTabtoSelection", new object[] { "Global::Ctrl+Shift+Alt+Space" } },
          { "Window.NextTabandAddtoSelection", new object[] { "Global::Ctrl+Shift+Alt+PgDn" } },
          { "Window.PreviousTabandAddtoSelection", new object[] { "Global::Ctrl+Shift+Alt+PgUp" } },
          { "View.AllWindows", new object[] { "Global::Shift+Alt+M" } },
          { "Window.KeepTabOpen", new object[] { "Global::Ctrl+Alt+Home" } },
          { "Window.ActivateWindowSearch", new object[] { "Global::Alt+ö" } },
          { "Window.ActivateQuickLaunch", new object[] { "Global::Ctrl+Q" } },
          { "Window.ActivateQuickLaunchPreviousCategory", new object[] { "Global::Ctrl+Shift+Q" } },
          { "Window.ActivateSolutionExplorerSearch", new object[] { "Global::Ctrl+ü" } },
          { "Edit.PeekDefinition", new object[] { "Text Editor::Alt+F12" } },
          { "Edit.PeekForward", new object[] { "Text Editor::Ctrl+Alt++" } },
          { "Edit.PeekBackward", new object[] { "Text Editor::Ctrl+Alt+-" } },
          { "Edit.MoveSelectedLinesUp", new object[] { "Text Editor::Alt+Up Arrow" } },
          { "Edit.MoveSelectedLinesDown", new object[] { "Text Editor::Alt+Down Arrow" } },
          { "Window.ShowDockMenu", new object[] { "Global::Alt+-" } },
          { "Tools.ForceGC", new object[] { "Global::Ctrl+Shift+Alt+F12, Ctrl+Shift+Alt+F12" } },
          { "View.ZoomIn", new object[] { "Global::Ctrl+Shift+." } },
          { "View.ZoomOut", new object[] { "Global::Ctrl+Shift+," } },
          { "Edit.ExpandAllOutlining", new object[] { "Text Editor::Ctrl+M, Ctrl+X" } },
          { "Edit.CollapseAllOutlining", new object[] { "Text Editor::Ctrl+M, Ctrl+A" } },
          { "Edit.ExpandCurrentRegion", new object[] { "Text Editor::Ctrl+M, Ctrl+E" } },
          { "Edit.CollapseCurrentRegion", new object[] { "Text Editor::Ctrl+M, Ctrl+S" } },
          { "Help.ViewHelp", new object[] { "Global::Ctrl+F1, V", "Global::Ctrl+F1, Ctrl+V" } },
          { "Help.AddandRemoveHelpContent", new object[] { "Global::Ctrl+Alt+F1", "Global::Ctrl+F1, M", "Global::Ctrl+F1, Ctrl+M" } },
          { "View.WebBrowser", new object[] { "Global::Ctrl+Alt+R", "Global::Ctrl+W, W", "Global::Ctrl+W, Ctrl+W" } },
          { "Debug.Breakpoints", new object[] { "Global::Ctrl+Alt+B", "Global::Ctrl+D, B", "Global::Ctrl+D, Ctrl+B" } },
          { "Debug.Disassembly", new object[] { "Global::Ctrl+Alt+D" } },
          { "Debug.Registers", new object[] { "Global::Ctrl+Alt+G", "Global::Ctrl+D, R", "Global::Ctrl+D, Ctrl+R" } },
          { "Debug.Modules", new object[] { "Global::Ctrl+Alt+U", "Global::Ctrl+D, M", "Global::Ctrl+D, Ctrl+M" } },
          { "Debug.ApplyCodeChanges", new object[] { "Global::Alt+F10" } },
          { "Debug.Processes", new object[] { "Global::Ctrl+Alt+Z", "Global::Ctrl+D, P", "Global::Ctrl+D, Ctrl+P" } },
          { "Debug.LocationToolbar.ToggleFlaggedThreads", new object[] { "Global::Ctrl+9" } },
          { "Debug.BreakatFunction", new object[] { "Global::Ctrl+B", "Global::Ctrl+D, N", "Global::Ctrl+D, Ctrl+N" } },
          { "Debug.StepIntoCurrentProcess", new object[] { "Global::Ctrl+Alt+F11" } },
          { "Debug.StepOverCurrentProcess", new object[] { "Global::Ctrl+Alt+F10" } },
          { "Debug.StepOutCurrentProcess", new object[] { "Global::Ctrl+Shift+Alt+F11" } },
          { "Debug.LocationToolbar.ToggleCurrentThreadFlaggedState", new object[] { "Global::Ctrl+8" } },
          { "Debug.StepIntoSpecific", new object[] { "Global::Shift+Alt+F11" } },
          { "EditorContextMenus.CodeWindow.Breakpoint.BreakpointEditlabels", new object[] { "Global::Alt+F9, L" } },
          { "DebuggerContextMenus.BreakpointsWindow.Delete", new object[] { "Global::Alt+F9, D" } },
          { "DebuggerContextMenus.BreakpointsWindow.GoToSourceCode", new object[] { "Global::Alt+F9, S" } },
          { "DebuggerContextMenus.BreakpointsWindow.GoToDisassembly", new object[] { "Global::Alt+F9, A" } },
          { "Debug.ToggleDisassembly", new object[] { "Global::Ctrl+F11", "Global::Ctrl+D, D", "Global::Ctrl+D, Ctrl+D" } },
          { "Debug.Memory1", new object[] { "Global::Ctrl+Alt+M, 1", "Global::Ctrl+D, Y", "Global::Ctrl+D, Ctrl+Y" } },
          { "Debug.Watch1", new object[] { "Global::Ctrl+Alt+W, 1", "Global::Ctrl+D, W", "Global::Ctrl+D, Ctrl+W" } },
          { "Debug.Memory2", new object[] { "Global::Ctrl+Alt+M, 2" } },
          { "Debug.Watch2", new object[] { "Global::Ctrl+Alt+W, 2" } },
          { "Debug.Memory3", new object[] { "Global::Ctrl+Alt+M, 3" } },
          { "Debug.Watch3", new object[] { "Global::Ctrl+Alt+W, 3" } },
          { "Debug.Memory4", new object[] { "Global::Ctrl+Alt+M, 4" } },
          { "Debug.Watch4", new object[] { "Global::Ctrl+Alt+W, 4" } },
          { "Build.RunCodeAnalysisonSolution", new object[] { "Global::Alt+F11" } },
          { "EditorContextMenus.CodeWindow.Execute", new object[] { "Global::Ctrl+Alt+F5" } },
          { "Image.CopyandOutlineSelection", new object[] { "VC Image Editor::Ctrl+Shift+U" } },
          { "Image.UseSelectionasBrush", new object[] { "VC Image Editor::Ctrl+U" } },
          { "SQL.Rename", new object[] { "Microsoft SQL Server Data Tools, Table Designer::Ctrl+R, R", "Microsoft SQL Server Data Tools, Table Designer::F2", "Microsoft SQL Server Data Tools, Table Designer::Ctrl+R, Ctrl+R", "Microsoft SQL Server Data Tools, T-SQL Editor::Ctrl+R, R", "Microsoft SQL Server Data Tools, T-SQL Editor::F2", "Microsoft SQL Server Data Tools, T-SQL Editor::Ctrl+R, Ctrl+R" } },
          { "TSqlEditorCloneQuery", new object[] { "Microsoft SQL Server Data Tools, T-SQL Editor::Ctrl+Alt+N", "Microsoft SQL Server Data Tools, T-SQL PDW Editor::Ctrl+Alt+N" } },
          { "SQL.TSqlEditorExecuteQuery", new object[] { "Microsoft SQL Server Data Tools, T-SQL Editor::Ctrl+Shift+E", "Microsoft SQL Server Data Tools, T-SQL PDW Editor::Ctrl+Shift+E" } },
          { "SQL.TSqlEditorCancelQuery", new object[] { "Microsoft SQL Server Data Tools, T-SQL Editor::Alt+Break", "Microsoft SQL Server Data Tools, T-SQL PDW Editor::Alt+Break" } },
          { "SQL.TSqlEditorShowEstimatedPlan", new object[] { "Microsoft SQL Server Data Tools, T-SQL Editor::Ctrl+D, E", "Microsoft SQL Server Data Tools, T-SQL PDW Editor::Ctrl+D, E" } },
          { "SQL.TSqlEditorToggleExecutionPlan", new object[] { "Microsoft SQL Server Data Tools, T-SQL Editor::Ctrl+D, A", "Microsoft SQL Server Data Tools, T-SQL PDW Editor::Ctrl+D, A" } },
          { "SQL.TSqlEditorResultsAsText", new object[] { "Microsoft SQL Server Data Tools, T-SQL Editor::Ctrl+D, T", "Microsoft SQL Server Data Tools, T-SQL PDW Editor::Ctrl+D, T" } },
          { "SQL.TSqlEditorResultsAsGrid", new object[] { "Microsoft SQL Server Data Tools, T-SQL Editor::Ctrl+D, G", "Microsoft SQL Server Data Tools, T-SQL PDW Editor::Ctrl+D, G" } },
          { "SQL.TSqlEditorResultsAsFile", new object[] { "Microsoft SQL Server Data Tools, T-SQL Editor::Ctrl+D, F", "Microsoft SQL Server Data Tools, T-SQL PDW Editor::Ctrl+D, F" } },
          { "SQL.TSqlEditorToggleResultsPane", new object[] { "Microsoft SQL Server Data Tools, T-SQL Editor::Ctrl+D, R", "Microsoft SQL Server Data Tools, T-SQL PDW Editor::Ctrl+D, R" } },
          { "SQL.ExecuteWithDebugger", new object[] { "Microsoft SQL Server Data Tools, T-SQL Editor::Alt+F5" } },
          { "MoveLeftEdgetotheleft", new object[] { "XAML UI Designer::Ctrl+Shift+," } },
          { "MoveLeftEdgetotheright", new object[] { "XAML UI Designer::Ctrl+Shift+." } },
          { "MoveRightEdgetotheleft", new object[] { "XAML UI Designer::Ctrl+Shift+Alt+," } },
          { "MoveRightEdgetotheright", new object[] { "XAML UI Designer::Ctrl+Shift+Alt+." } },
          { "Team.TeamExplorerSearch", new object[] { "Global::Ctrl+ä" } },
          { "OtherContextMenus.JSONContext.ReloadSchemas", new object[] { "JSON Editor::Ctrl+Shift+J" } },
          { "Debug.ParallelWatch1", new object[] { "Global::Ctrl+Shift+D, 1" } },
          { "SQL.MovetoSchema", new object[] { "Microsoft SQL Server Data Tools, Table Designer::Ctrl+R, M", "Microsoft SQL Server Data Tools, Table Designer::Ctrl+R, Ctrl+M", "Microsoft SQL Server Data Tools, T-SQL Editor::Ctrl+R, M", "Microsoft SQL Server Data Tools, T-SQL Editor::Ctrl+R, Ctrl+M" } },
          { "EditorContextMenus.CodeWindow.GoToView", new object[] { "Global::Ctrl+M, Ctrl+G" } },
          { "SQL.ExpandWildcards", new object[] { "Microsoft SQL Server Data Tools, Table Designer::Ctrl+R, E", "Microsoft SQL Server Data Tools, Table Designer::Ctrl+R, Ctrl+E", "Microsoft SQL Server Data Tools, T-SQL Editor::Ctrl+R, E", "Microsoft SQL Server Data Tools, T-SQL Editor::Ctrl+R, Ctrl+E" } },
          { "OtherContextMenus.HTMLContext.GoToController", new object[] { "HTML Editor::Ctrl+M, Ctrl+G", "HTML Editor Source View::Ctrl+M, Ctrl+G" } },
          { "SQL.FullyqualifyNames", new object[] { "Microsoft SQL Server Data Tools, Table Designer::Ctrl+R, Q", "Microsoft SQL Server Data Tools, Table Designer::Ctrl+R, Ctrl+Q", "Microsoft SQL Server Data Tools, T-SQL Editor::Ctrl+R, Q", "Microsoft SQL Server Data Tools, T-SQL Editor::Ctrl+R, Ctrl+Q" } },
          { "SQL.QueryResultsStop", new object[] { "Query Results::Alt+Break" } },
          { "SQL.QueryResultsRefresh", new object[] { "Query Results::Shift+Alt+R" } },
          { "SQL.QueryResultsNewRow", new object[] { "Query Results::Alt+End" } },
          { "OtherContextMenus.FSIConsoleContext.CancelInteractiveEvaluation", new object[] { "F# Interactive::Ctrl+Break" } },
          { "View.CallHierarchy", new object[] { "Global::Ctrl+W, K", "Global::Ctrl+W, Ctrl+K" } },
          { "Project.ClassWizard", new object[] { "Global::Ctrl+Shift+X" } },
          { "Debug.ParallelWatch2", new object[] { "Global::Ctrl+Shift+D, 2" } },
          { "CommitAllEdits", new object[] { "Microsoft SQL Server Data Tools, Table Designer::Shift+Alt+U", "Microsoft SQL Server Data Tools, T-SQL Editor::Shift+Alt+U" } },
          { "Debug.ParallelWatch3", new object[] { "Global::Ctrl+Shift+D, 3" } },
          { "OtherContextMenus.HTMLContext.ViewinPageInspector", new object[] { "Text Editor::Ctrl+K, Ctrl+G" } },
          { "ClassViewContextMenus.ClassViewProject.View.ViewinPageInspector", new object[] { "Solution Explorer::Ctrl+K, Ctrl+G" } },
          { "Debug.ParallelWatch4", new object[] { "Global::Ctrl+Shift+D, 4" } },
          { "Diff.SwitchBetweenLeftAndRight", new object[] { "Difference Viewer::Ctrl+^, Ctrl+Tab" } },
          { "OtherContextMenus.DbTableContext.Add.Column", new object[] { "DataSet Editor::Ctrl+L" } },
          { "OtherContextMenus.ColumnContext.InsertColumn", new object[] { "DataSet Editor::Ins" } },
          { "Debug.RefreshWindowsapp", new object[] { "Global::Ctrl+Shift+R" } },
          { "Debug.DebugWindowsPhoneInternetExplorer", new object[] { "Global::Ctrl+Shift+P" } },
          { "File.NewWebSite", new object[] { "Global::Shift+Alt+N" } },
          { "File.OpenWebSite", new object[] { "Global::Shift+Alt+O" } },
          { "Edit.RemoveRow", new object[] { "Managed Resources Editor::Ctrl+Del", "Settings Designer::Ctrl+Del" } },
          { "Edit.NavigateTo", new object[] { "Global::Ctrl+," } },
          { "Edit.EditCell", new object[] { "Managed Resources Editor::F2", "Settings Designer::F2" } },
          { "View.DataSources", new object[] { "Global::Shift+Alt+D" } },
          { "View.EntityDataModelMappingDetails", new object[] { "ADO.NET Entity Data Model Designer::Ctrl+2" } },
          { "View.EntityDataModelBrowser", new object[] { "ADO.NET Entity Data Model Designer::Ctrl+1" } },
          { "View.F#Interactive", new object[] { "Global::Ctrl+Alt+F" } },
          { "EditorContextMenus.CodeWindow.ExecuteInInteractive", new object[] { "Text Editor::Alt+Enter" } },
          { "EditorContextMenus.CodeWindow.ExecuteLineInInteractive", new object[] { "Text Editor::Alt+ä" } },
          { "View.SQLServerObjectExplorer", new object[] { "Global::Ctrl+^, Ctrl+S" } },
          { "View.Notifications", new object[] { "Global::Ctrl+W, N", "Global::Ctrl+W, Ctrl+N" } },
          { "SolutionExplorer.PendingChangesFilter", new object[] { "Global::Ctrl+ß, P", "Global::Ctrl+ß, Ctrl+P" } },
          { "SolutionExplorer.OpenFilesFilter", new object[] { "Global::Ctrl+ß, O", "Global::Ctrl+ß, Ctrl+O" } },
          { "SolutionExplorer.SyncWithActiveDocument", new object[] { "Global::Ctrl+ß, S", "Global::Ctrl+ß, Ctrl+S" } },
          { "View.SynchronizeViews", new object[] { "HTML Editor Source View::Ctrl+Shift+Y" } },
          { "Edit.RefreshRemoteReferences", new object[] { "Global::Ctrl+Shift+J" } },
          { "View.PendingCheckins", new object[] { "Global::Ctrl+W, G", "Global::Ctrl+W, Ctrl+G" } },
          { "EditorContextMenus.CodeWindow.ToggleHeaderCodeFile", new object[] { "Global::Ctrl+K, Ctrl+O" } },
          { "Debug.StopPerformanceAnalysis", new object[] { "Global::Shift+Alt+F2" } },
          { "ProjectandSolutionContextMenus.Item.MoveUp", new object[] { "Global::Alt+Up Arrow" } },
          { "ProjectandSolutionContextMenus.Item.MoveDown", new object[] { "Global::Alt+Down Arrow" } },
          { "WorkflowDesigner.GoToParent", new object[] { "Workflow Designer::Ctrl+E, Ctrl+P", "Workflow Designer::Ctrl+E, P" } },
          { "WorkflowDesigner.ExpandInPlace", new object[] { "Workflow Designer::Ctrl+E, Ctrl+E", "Workflow Designer::Ctrl+E, E" } },
          { "WorkflowDesigner.Collapse", new object[] { "Workflow Designer::Ctrl+E, Ctrl+C", "Workflow Designer::Ctrl+E, C" } },
          { "WorkflowDesigner.CollapseAll", new object[] { "Workflow Designer::Ctrl+E, Ctrl+Y", "Workflow Designer::Ctrl+E, Y" } },
          { "WorkflowDesigner.Restore", new object[] { "Workflow Designer::Ctrl+E, Ctrl+R", "Workflow Designer::Ctrl+E, R" } },
          { "WorkflowDesigner.ExpandAll", new object[] { "Workflow Designer::Ctrl+E, Ctrl+X", "Workflow Designer::Ctrl+E, X" } },
          { "WorkflowDesigner.NavigateThroughDesigner", new object[] { "Workflow Designer::Ctrl+Alt+F6" } },
          { "WorkflowDesigner.ShowHideArgumentDesigner", new object[] { "Workflow Designer::Ctrl+E, Ctrl+A", "Workflow Designer::Ctrl+E, A" } },
          { "WorkflowDesigner.ShowHideVariableDesigner", new object[] { "Workflow Designer::Ctrl+E, Ctrl+V", "Workflow Designer::Ctrl+E, V" } },
          { "WorkflowDesigner.ShowHideImportsDesigner", new object[] { "Workflow Designer::Ctrl+E, Ctrl+I", "Workflow Designer::Ctrl+E, I" } },
          { "WorkflowDesigner.ShowHideOverviewMap", new object[] { "Workflow Designer::Ctrl+E, Ctrl+O", "Workflow Designer::Ctrl+E, O" } },
          { "WorkflowDesigner.CreateVariable", new object[] { "Workflow Designer::Ctrl+E, Ctrl+N", "Workflow Designer::Ctrl+E, N" } },
          { "WorkflowDesigner.ConnectNodes", new object[] { "Workflow Designer::Ctrl+E, Ctrl+F", "Workflow Designer::Ctrl+E, F" } },
          { "WorkflowDesigner.ZoomIn", new object[] { "Workflow Designer::Ctrl+Num +" } },
          { "WorkflowDesigner.ZoomOut", new object[] { "Workflow Designer::Ctrl+Num -" } },
          { "WorkflowDesigner.MoveFocus", new object[] { "Workflow Designer::Ctrl+E, Ctrl+M", "Workflow Designer::Ctrl+E, M" } },
          { "WorkflowDesigner.ToggleSelection", new object[] { "Workflow Designer::Ctrl+E, Ctrl+S", "Workflow Designer::Ctrl+E, S" } },
          { "OtherContextMenus.ORDesignerContextMenu.HideMethodsPane", new object[] { "VisualStudio::Ctrl+1" } },
          { "Analyze.NavigateBackward", new object[] { "Global::Shift+Alt+3" } },
          { "Analyze.NavigateForward", new object[] { "Global::Shift+Alt+4" } },
          { "QueryDesigner.JoinMode", new object[] { "Query Designer::Ctrl+Shift+J", "View Designer::Ctrl+Shift+J" } },
          { "QueryDesigner.CancelRetrievingData", new object[] { "Query Designer::Ctrl+T", "View Designer::Ctrl+T" } },
          { "Edit.ExpandCollapseBaseTypeList", new object[] { "Class Diagram::Shift+Alt+B" } },
          { "Edit.NavigateToLollipop", new object[] { "Class Diagram::Shift+Alt+L" } },
          { "ClassDiagram.Collapse", new object[] { "Class Diagram::Num -" } },
          { "ClassDiagram.Expand", new object[] { "Class Diagram::Num +" } },
          { "Edit.RemovefromDiagram", new object[] { "Class Diagram::Del" } },
          { "ArchitectureContextMenus.DirectedGraphContextMenu.Advanced.Select.IncomingDependencies", new object[] { "Graph Document Editor::I" } },
          { "ArchitectureContextMenus.DirectedGraphContextMenu.Advanced.Select.OutgoingDependencies", new object[] { "Graph Document Editor::O" } },
          { "ArchitectureContextMenus.DirectedGraphContextMenu.Advanced.Select.BothDependencies", new object[] { "Graph Document Editor::B" } },
          { "ArchitectureContextMenus.DirectedGraphContextMenu.NewComment", new object[] { "Graph Document Editor::Ctrl+Shift+K", "Graph Document Editor::Ctrl+E, C" } },
          { "ArchitectureContextMenus.DirectedGraphContextMenu.Remove", new object[] { "Graph Document Editor::Del" } },
          { "ArchitectureContextMenus.DirectedGraphContextMenu.Rename", new object[] { "Graph Document Editor::F2" } },
          { "ArchitectureContextMenus.DirectedGraphContextMenu.Advanced.Add.AddNode", new object[] { "Graph Document Editor::Ins" } },
          { "SQL.SSDTSchemaCompareWriteUpdates", new object[] { "Microsoft SQL Server Data Tools, Schema Compare::Shift+Alt+U" } },
          { "SQL.SSDTSchemaCompareStop", new object[] { "Microsoft SQL Server Data Tools, Schema Compare::Alt+Break" } },
          { "SQL.SSDTSchemaCompareNextChange", new object[] { "Microsoft SQL Server Data Tools, Schema Compare::Shift+Alt+." } },
          { "SQL.SSDTSchemaComparePreviousChange", new object[] { "Microsoft SQL Server Data Tools, Schema Compare::Shift+Alt+," } },
          { "SQL.SSDTSchemaCompareCompare", new object[] { "Microsoft SQL Server Data Tools, Schema Compare::Shift+Alt+C" } },
          { "SQL.SSDTSchemaCompareGenerateScript", new object[] { "Microsoft SQL Server Data Tools, Schema Compare::Shift+Alt+G" } },
          { "Debug.Graphics.StartDiagnostics", new object[] { "Global::Alt+F5" } },
          { "Debug.DiagnosticsHub.Launch", new object[] { "Global::Alt+F2" } },
          { "Debug.DiagnosticsHub.StopCollection", new object[] { "Global::Ctrl+Alt+F2" } },
          { "PageInspector.Minimize", new object[] { "Page Inspector::F12" } },
          { "OtherContextMenus.BrowserLink.RefreshLinkedBrowsers", new object[] { "Global::Ctrl+Alt+Enter" } },
          { "Table.ColumntotheLeft", new object[] { "HTML Editor Design View::Ctrl+Alt+Left Arrow" } },
          { "Table.ColumntotheRight", new object[] { "HTML Editor Design View::Ctrl+Alt+Right Arrow" } },
          { "Table.RowAbove", new object[] { "HTML Editor Design View::Ctrl+Alt+Up Arrow" } },
          { "Table.RowBelow", new object[] { "HTML Editor Design View::Ctrl+Alt+Down Arrow" } },
          { "View.ASP.NETNonvisualControls", new object[] { "HTML Editor Design View::Ctrl+Shift+N" } },
          { "Project.Publishselectedfiles", new object[] { "Global::Alt+ü, Alt+P" } },
          { "Project.Previewchanges", new object[] { "Global::Alt+ü, Alt+C" } },
          { "Project.Replaceselectedfilesfromserver", new object[] { "Global::Alt+ü, Alt+R" } },
          { "MicrosoftAzure.ShowMobileServiceScriptErrorDetails", new object[] { "Global::Ctrl+Num *, Ctrl+D" } },
          { "MicrosoftAzure.RetryMobileServiceScriptOperation", new object[] { "Global::Ctrl+Num *, Ctrl+R" } },
          { "Debug.StartWindowsPhoneApplicationAnalysis", new object[] { "Global::Alt+F1" } },
          { "Design.ZoomIn", new object[] { "XAML UI Designer::Ctrl+Alt++" } },
          { "Design.ZoomOut", new object[] { "XAML UI Designer::Ctrl+Alt+-" } },
          { "Design.FitAll", new object[] { "XAML UI Designer::Ctrl+0" } },
          { "Design.ShowHandles", new object[] { "XAML UI Designer::F9" } },
          { "Format.EditText", new object[] { "XAML UI Designer::F2" } },
          { "Format.ResetAll", new object[] { "XAML UI Designer::Ctrl+Shift+R" } },
          { "Diff.SideBySideView", new object[] { "Difference Viewer::Ctrl+^, Ctrl+2" } },
          { "Diff.InlineView", new object[] { "Difference Viewer::Ctrl+^, Ctrl+1" } },
          { "Diff.LeftOnlyView", new object[] { "Difference Viewer::Ctrl+^, Ctrl+3" } },
          { "Diff.RightOnlyView", new object[] { "Difference Viewer::Ctrl+^, Ctrl+4" } },
          { "Diff.PreviousDifference", new object[] { "Difference Viewer::Shift+F8" } },
          { "Diff.NextDifference", new object[] { "Difference Viewer::F8" } },
          { "Diff.IgnoreTrimWhitespace", new object[] { "Difference Viewer::Ctrl+^, Ctrl+Space" } },
          { "Diff.SynchronizeViewToggle", new object[] { "Difference Viewer::Ctrl+^, Ctrl+Down Arrow" } },
          { "Resources.Strings", new object[] { "Managed Resources Editor::Ctrl+1" } },
          { "Resources.Images", new object[] { "Managed Resources Editor::Ctrl+2" } },
          { "Resources.Icons", new object[] { "Managed Resources Editor::Ctrl+3" } },
          { "Resources.Audio", new object[] { "Managed Resources Editor::Ctrl+4" } },
          { "Resources.Files", new object[] { "Managed Resources Editor::Ctrl+5" } },
          { "Resources.Other", new object[] { "Managed Resources Editor::Ctrl+6" } },
          { "OtherContextMenus.MicrosoftDataEntityDesignContext.RemovefromDiagram", new object[] { "ADO.NET Entity Data Model Designer::Shift+Del" } },
          { "OtherContextMenus.MicrosoftDataEntityDesignContext.Refactor.Rename", new object[] { "ADO.NET Entity Data Model Designer::Ctrl+R, R" } },
          { "OtherContextMenus.MicrosoftDataEntityDesignContext.AddNewDiagram", new object[] { "Global::Ins" } },
          { "OtherContextMenus.MicrosoftDataEntityDesignContext.MoveProperties.ToTop", new object[] { "ADO.NET Entity Data Model Designer::Alt+Home" } },
          { "OtherContextMenus.MicrosoftDataEntityDesignContext.MoveProperties.ToBottom", new object[] { "ADO.NET Entity Data Model Designer::Alt+End" } },
          { "OtherContextMenus.MicrosoftDataEntityDesignContext.MoveProperties.Up", new object[] { "ADO.NET Entity Data Model Designer::Alt+Up Arrow" } },
          { "OtherContextMenus.MicrosoftDataEntityDesignContext.MoveProperties.Down", new object[] { "ADO.NET Entity Data Model Designer::Alt+Down Arrow" } },
          { "OtherContextMenus.MicrosoftDataEntityDesignContext.MoveProperties.Up5", new object[] { "ADO.NET Entity Data Model Designer::Alt+PgUp" } },
          { "OtherContextMenus.MicrosoftDataEntityDesignContext.MoveProperties.Down5", new object[] { "ADO.NET Entity Data Model Designer::Alt+PgDn" } },
          { "View.ReportData", new object[] { "Report Designer::Ctrl+Alt+D" } },
          { "TeamFoundationContextMenus.Annotate.TfsAnnotateMovePreviousRegion", new object[] { "Text Editor::Alt+PgUp" } },
          { "TeamFoundationContextMenus.Annotate.TfsAnnotateMoveNextRegion", new object[] { "Text Editor::Alt+PgDn" } },
          { "TeamFoundationContextMenus.MergeContextMenu.SetFocusonLeftWindow", new object[] { "Merge Editor Window::Alt+1" } },
          { "TeamFoundationContextMenus.MergeContextMenu.SetFocusonResultWindow", new object[] { "Merge Editor Window::Alt+2" } },
          { "TeamFoundationContextMenus.MergeContextMenu.SetFocusonRightWindow", new object[] { "Merge Editor Window::Alt+3" } },
          { "TeamFoundationContextMenus.Commands.GoToPendingChanges", new object[] { "Global::Ctrl+0, Ctrl+P", "Global::Ctrl+0, P" } },
          { "TeamFoundationContextMenus.Commands.GoToMyWork", new object[] { "Global::Ctrl+0, Ctrl+M", "Global::Ctrl+0, M" } },
          { "TeamFoundationContextMenus.MyWorkPageInProgress.TfsContextMyWorkPageCreateCopyWI", new object[] { "Team Explorer::Shift+Alt+C" } },
          { "TeamFoundationContextMenus.MyWorkPageInProgress.TfsContextMyWorkPageNewLinkedWI", new object[] { "Team Explorer::Shift+Alt+L" } },
          { "TeamFoundationContextMenus.Commands.GoToBuilds", new object[] { "Global::Ctrl+0, Ctrl+B", "Global::Ctrl+0, B" } },
          { "TeamFoundationContextMenus.Commands.GoToDocuments", new object[] { "Global::Ctrl+0, Ctrl+D", "Global::Ctrl+0, D" } },
          { "TeamFoundationContextMenus.Commands.GoToReports", new object[] { "Global::Ctrl+0, Ctrl+R", "Global::Ctrl+0, R" } },
          { "View.TfsTeamExplorer", new object[] { "Global::Ctrl+^, Ctrl+M" } },
          { "TeamFoundationContextMenus.Commands.GoToHome", new object[] { "Global::Ctrl+0, Ctrl+H", "Global::Ctrl+0, H" } },
          { "TeamFoundationContextMenus.Commands.GoToSettings", new object[] { "Global::Ctrl+0, Ctrl+S", "Global::Ctrl+0, S" } },
          { "TeamFoundationContextMenus.Commands.GoToWebAccess", new object[] { "Global::Ctrl+0, Ctrl+A", "Global::Ctrl+0, A" } },
          { "TeamFoundationContextMenus.Commands.GoToConnect", new object[] { "Global::Ctrl+0, Ctrl+C", "Global::Ctrl+0, C" } },
          { "TeamFoundationContextMenus.Commands.TeamExplorerNavigateBackward", new object[] { "Team Explorer::Alt+Left Arrow" } },
          { "TeamFoundationContextMenus.Commands.TeamExplorerNavigateForward", new object[] { "Team Explorer::Alt+Right Arrow" } },
          { "TeamFoundationContextMenus.Commands.GoToTeamExplorerNavigation", new object[] { "Team Explorer::Alt+Home" } },
          { "TeamFoundationContextMenus.Commands.GoToTeamExplorerPageContent", new object[] { "Team Explorer::Alt+0" } },
          { "TeamFoundationContextMenus.Commands.GoToTeamExplorerPreviousSectionContent", new object[] { "Team Explorer::Alt+Up Arrow" } },
          { "TeamFoundationContextMenus.Commands.GoToTeamExplorerNextSectionContent", new object[] { "Team Explorer::Alt+Down Arrow" } },
          { "TeamFoundationContextMenus.Commands.GoToTeamExplorerSection1Content", new object[] { "Team Explorer::Alt+1" } },
          { "TeamFoundationContextMenus.Commands.GoToTeamExplorerSection2Content", new object[] { "Team Explorer::Alt+2" } },
          { "TeamFoundationContextMenus.Commands.GoToTeamExplorerSection3Content", new object[] { "Team Explorer::Alt+3" } },
          { "TeamFoundationContextMenus.Commands.GoToTeamExplorerSection4Content", new object[] { "Team Explorer::Alt+4" } },
          { "TeamFoundationContextMenus.Commands.GoToTeamExplorerSection5Content", new object[] { "Team Explorer::Alt+5" } },
          { "TeamFoundationContextMenus.Commands.GoToTeamExplorerSection6Content", new object[] { "Team Explorer::Alt+6" } },
          { "TeamFoundationContextMenus.Commands.GoToTeamExplorerSection7Content", new object[] { "Team Explorer::Alt+7" } },
          { "TeamFoundationContextMenus.Commands.GoToTeamExplorerSection8Content", new object[] { "Team Explorer::Alt+8" } },
          { "TeamFoundationContextMenus.Commands.GoToTeamExplorerSection9Content", new object[] { "Team Explorer::Alt+9" } },
          { "Edit.RefreshWorkItem", new object[] { "Work Item Editor::F5" } },
          { "Team.GotoPreviousWorkItem", new object[] { "Work Item Results View::Shift+Alt+P" } },
          { "Team.GotoNextWorkItem", new object[] { "Work Item Results View::Shift+Alt+N" } },
          { "Team.Refresh", new object[] { "Work Item Query View::F5", "Work Item Results View::F5" } },
          { "Edit.CreateCopyofWorkItem", new object[] { "Work Item Query View::Shift+Alt+C", "Work Item Results View::Shift+Alt+C", "Work Item Editor::Shift+Alt+C" } },
          { "Team.NewLinkedWorkItem", new object[] { "Work Item Query View::Shift+Alt+L", "Work Item Results View::Shift+Alt+L", "Work Item Editor::Shift+Alt+L" } },
          { "TeamFoundationContextMenus.Commands.GoToWorkItems", new object[] { "Global::Ctrl+0, Ctrl+W", "Global::Ctrl+0, W" } },
          { "Edit.Outdent", new object[] { "Work Item Query View::Shift+Alt+Left Arrow", "Work Item Results View::Shift+Alt+Left Arrow" } },
          { "Edit.Indent", new object[] { "Work Item Query View::Shift+Alt+Right Arrow", "Work Item Results View::Shift+Alt+Right Arrow" } },
          { "Window.Toggle", new object[] { "Work Item Query View::Shift+Alt+V", "Work Item Results View::Shift+Alt+V" } },
          { "TestExplorer.OpenTest", new object[] { "Test Explorer::F12" } },
          { "TestExplorer.RunAllTests", new object[] { "Global::Ctrl+R, A" } },
          { "TestExplorer.RepeatLastRun", new object[] { "Global::Ctrl+R, L" } },
          { "TestExplorer.DebugAllTests", new object[] { "Global::Ctrl+R, Ctrl+A" } },
          { "TestExplorer.RunAllTestsInContext", new object[] { "Global::Ctrl+R, T" } },
          { "TestExplorer.DebugAllTestsInContext", new object[] { "Global::Ctrl+R, Ctrl+T" } },
          { "Debug.SelectElement", new object[] { "DOM Explorer::Ctrl+B" } },
          { "Debug.Refresh", new object[] { "DOM Explorer::F5" } },
          { "Debug.ShowLayout", new object[] { "DOM Explorer::Ctrl+Shift+I" } },
          { "Debug.ShowAll", new object[] { "Global::Ctrl+Alt+V, D" } },
          { "Debug.JavaScriptConsole", new object[] { "Global::Ctrl+Alt+V, C" } },
          { "Debug.Tasks", new object[] { "Global::Ctrl+Shift+D, K", "Global::Ctrl+D, K", "Global::Ctrl+D, Ctrl+K" } },
          { "Debug.ParallelStacks", new object[] { "Global::Ctrl+Shift+D, S" } },
          { "XML.StartXSLTDebugging", new object[] { "XML (Text) Editor::Alt+F5" } },
          { "XML.StartXSLTWithoutDebugging", new object[] { "XML (Text) Editor::Ctrl+Alt+F5" } },
          { "XsdDesigner.ShowStartView", new object[] { "XML Schema Designer::Ctrl+1" } },
          { "XsdDesigner.ShowContentModelView", new object[] { "XML Schema Designer::Ctrl+2" } },
          { "XsdDesigner.ShowGraphView", new object[] { "XML Schema Designer::Ctrl+3" } },
          { "GraphView.LefttoRight", new object[] { "XML Schema Designer::Alt+Right Arrow" } },
          { "GraphView.RighttoLeft", new object[] { "XML Schema Designer::Alt+Left Arrow" } },
          { "GraphView.ToptoBottom", new object[] { "XML Schema Designer::Alt+Down Arrow" } },
          { "GraphView.BottomtoTop", new object[] { "XML Schema Designer::Alt+Up Arrow" } },
          { "OtherContextMenus.GraphView.RemovefromWorkspace", new object[] { "XML Schema Designer::Del" } },
          { "Edit.GoToFindCombo", new object[] { "Global::Ctrl+#" } },
          { "Debug.LocationToolbar.ProcessCombo", new object[] { "Global::Ctrl+5" } },
          { "Debug.LocationToolbar.ThreadCombo", new object[] { "Global::Ctrl+6" } },
          { "Debug.LocationToolbar.StackFrameCombo", new object[] { "Global::Ctrl+7" } },
          { "TSqlEditorDatabaseCombo", new object[] { "Microsoft SQL Server Data Tools, T-SQL Editor::Shift+Alt+PgDn", "Microsoft SQL Server Data Tools, T-SQL PDW Editor::Shift+Alt+PgDn" } },
          { "ViewFileInScriptPanel", new object[] { "Microsoft SQL Server Data Tools, Table Designer::Shift+Alt+PgDn" } }
        };
  }
}